import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createWorld} from '../packages/worldgen/src/index.js';import {advance,applyProposal,validateWorld} from '../packages/engine/src/index.js';import {advanceAir,airTotals,airNeighborBearings,previewAir} from '../packages/engine/src/air.js';import {readValue} from '../packages/engine/src/extensions.js';import {appearance} from '../packages/globe/src/appearance.js';import {ProposalSchema,type World,type Operation} from '../packages/contracts/src/index.js';import {WorldStore,stateHash} from '../apps/server/src/store.js';import {PromptService,forecast} from '../apps/server/src/prompts.js';import {unpackBundle} from '../apps/server/src/portable.js';
const proposal=(w:World,operations:Operation[])=>ProposalSchema.parse({id:`edit-${w.history.length}`,worldId:w.id,expectedRevision:w.revision,summary:'Air change',operations});const edit=(w:World,ops:Operation[])=>applyProposal(w,proposal(w,ops));
const setup=()=>{let w=createWorld({id:'air',name:'Air',seed:'air',frequency:2});return edit(w,[{kind:'air-configure',tileId:0,expectedVersion:0,enabled:true,settings:{mixingPermille:0,removalPermille:0}}]);};
test('seeded spherical winds, calm mixing, reversal and one-hop transport are deterministic and conserved',()=>{const w=setup();assert.deepEqual(w.tiles.map(t=>t.air),setup().tiles.map(t=>t.air));for(const t of w.tiles){const edges=airNeighborBearings(w,t.id);assert.equal(edges.length,w.cells[t.id].neighbors.length);assert.ok(edges.every(e=>Number.isFinite(e.bearingDeg)&&e.bearingDeg>=0&&e.bearingDeg<360));}
 const bearing=Math.round(airNeighborBearings(w,0)[0].bearingDeg)%360,loaded=edit(w,[{kind:'air-release',tileId:0,delta:10000},{kind:'air-wind',tileId:0,bearingDeg:bearing,transportPermille:500}]);const a=advance(loaded),b=advance(edit(loaded,[{kind:'air-wind',tileId:0,bearingDeg:(bearing+180)%360,transportPermille:500}]));assert.equal(airTotals(a).load,10000);assert.equal(a.tiles[0].air!.load,5000);assert.notDeepEqual(a.air!.lastDay!.transfers,b.air!.lastDay!.transfers);assert.ok(a.air!.lastDay!.transfers.every(e=>e.from===0&&w.cells[0].neighbors.includes(e.to)));assert.equal(stateHash(advance(loaded)),stateHash(a));
 const calm=edit(loaded,[{kind:'air-wind',tileId:0,bearingDeg:0,transportPermille:0}]);assert.equal(advance(calm).tiles[0].air!.load,10000);const mixing=edit(calm,[{kind:'air-configure',tileId:0,expectedVersion:1,enabled:true,settings:{mixingPermille:100,removalPermille:0}}]);const mixed=advance(mixing);assert.equal(mixed.tiles[0].air!.load,9000);assert.equal(mixed.air!.lastDay!.transfers.length,w.cells[0].neighbors.length);assert.ok(mixed.air!.lastDay!.transfers.every(e=>e.wind===0));
});
test('emission, cleanup, removal, pause and stopping a source account for every unit',()=>{let w=setup();w=edit(w,[{kind:'air-source',tileId:0,unitsPerDay:100},{kind:'air-wind',tileId:0,bearingDeg:0,transportPermille:0},{kind:'air-configure',tileId:0,expectedVersion:1,enabled:true,settings:{mixingPermille:0,removalPermille:100}}]);w=advance(w);assert.equal(w.tiles[0].air!.load,90);assert.equal(w.air!.lastDay!.removed,10);w=edit(w,[{kind:'air-source',tileId:0,unitsPerDay:0}]);assert.equal(w.tiles[0].air!.load,90);w=advance(w);assert.equal(w.tiles[0].air!.load,81);w=edit(w,[{kind:'air-release',tileId:0,delta:-80}]);assert.equal(w.tiles[0].air!.load,1);assert.throws(()=>edit(w,[{kind:'air-release',tileId:0,delta:-2}]),/capacity/);w=edit(w,[{kind:'air-source',tileId:0,unitsPerDay:100},{kind:'air-configure',tileId:0,expectedVersion:2,enabled:false,settings:{mixingPermille:0,removalPermille:100}}]);const paused=advance(w);assert.equal(paused.tiles[0].air!.load,1);assert.equal(paused.air!.lastDay,undefined);assert.throws(()=>previewAir(paused,0),/Enable/);});
test('capacity rejects emissions explicitly; competing transfers retain excess at source, never overfill or forward',()=>{let w=setup();w=edit(w,[{kind:'air-release',tileId:0,delta:1e9},{kind:'air-source',tileId:0,unitsPerDay:1000}]);for(const t of w.tiles){t.air!.load=1e9;t.air!.windPermille=900;}w=advance(w);assert.equal(w.air!.lastDay!.rejectedEmission,1000);assert.equal(w.air!.lastDay!.transferred,0);assert.equal(w.air!.lastDay!.after,w.tiles.length*1e9);
 const open=w.cells[0].neighbors[0];w.tiles[open].air!.load=999999997;const n=structuredClone(w);n.tick++;advanceAir(n);assert.equal(n.air!.lastDay!.transfers.filter(e=>e.to===open).reduce((a,e)=>a+e.amount,0),3);assert.ok(n.tiles.every(t=>t.air!.load<=1e9));validateWorld(n);assert.equal(airTotals(n).load,airTotals(w).load);
});
test('air ignores borders, terrain and oceans, does no damage, and is readable by overlays and custom rules',()=>{const legacy=createWorld({id:'air',name:'Air',seed:'air',frequency:2});const w=edit(legacy,[{kind:'air-configure',tileId:0,expectedVersion:0,enabled:true,settings:{mixingPermille:100,removalPermille:0}},{kind:'air-release',tileId:0,delta:10000}]);for(const t of w.tiles){t.travelAllowed=false;t.communication=false;}const baseline=structuredClone(w);delete baseline.air;for(const t of baseline.tiles)delete t.air;const expected=advance(baseline),actual=advance(w);assert.equal(actual.air!.lastDay!.transfers.length,w.cells[0].neighbors.length);const stripped=structuredClone(actual);delete stripped.air;for(const t of stripped.tiles)delete t.air;assert.deepEqual(stripped,expected);assert.equal(readValue(w,0,{source:'airLoad',sample:'self'}),10000);assert.ok(readValue(w,0,{source:'airDensity',sample:'neighbors-max'})===0);assert.notEqual(appearance(w,w.tiles[0],'air').color,appearance(w,w.tiles[w.cells[0].neighbors[0]],'air').color);assert.ok(appearance(w,w.tiles[0],'wind').color.startsWith('hsl'));assert.equal(advance(legacy).air,undefined);
});
test('air previews, validation, scopes and persistence preserve replay and do not mutate the saved world',async()=>{const root=await mkdtemp(join(tmpdir(),'logos-air-')),store=new WorldStore(root);let w=setup();try{await store.save(w);const p=proposal(w,[{kind:'air-release',tileId:0,delta:10000}]),hash=stateHash(w);assert.equal(forecast(w,p).airPreview!.applied.load,10000);assert.equal(stateHash(w),hash);w=applyProposal(w,p);await store.save(w,{kind:'proposal',proposal:p});const read=previewAir(w,0),next=advance(w);assert.deepEqual(read.budget,next.air!.lastDay!.tiles[0]);assert.equal((await store.load(w.id)).tick,w.tick);w=next;for(let i=0;i<9;i++)w=advance(w);await store.save(w,{kind:'step',days:10});assert.equal((await store.verifyHistory(w.id)).hash,stateHash(w));const cp=await store.checkpoint(w,'Air');assert.equal(stateHash((await store.readCheckpoint(w.id,cp.id)).world),stateHash(w));assert.equal(stateHash((await unpackBundle(await store.exportBundle(w.id))).world),stateHash(w));const corrupt=structuredClone(w);corrupt.air!.lastDay!.tiles[0].incoming++;assert.throws(()=>validateWorld(corrupt),/budget/);
 for(const [scope,kind,status] of [['tile','air-configure','failed'],['world','air-configure','complete'],['tile','air-source','complete']] as const){const service=new PromptService(store,{name:'Air fixture',async generate(){return {kind:'proposal',message:'Air change',assumptions:[],operations:[kind==='air-configure'?{kind,tileId:0,expectedVersion:1,enabled:true,settings:{mixingPermille:20,removalPermille:10}}:{kind,tileId:0,unitsPerDay:100}]};}});try{const id=`${scope}-${kind}`;await service.start(w,{id,worldId:w.id,expectedRevision:w.revision,tileId:0,scope,mode:'propose',message:'Change air'});while(service.busy)await new Promise(r=>setTimeout(r,5));assert.equal((await service.get(w,id)).status,status);}finally{await service.close();}}assert.equal(stateHash(await store.load(w.id)),stateHash(w));
 }finally{await rm(root,{recursive:true,force:true});}});
test('pollution and weather remain deterministic and balanced across a long combined run',()=>{let w=setup();w=edit(w,[{kind:'air-configure',tileId:0,expectedVersion:1,enabled:true,settings:{mixingPermille:20,removalPermille:10}},{kind:'air-source',tileId:0,unitsPerDay:1000},{kind:'air-release',tileId:0,delta:12345}]);const initial=structuredClone(w);let input=12345,removed=0;for(let i=0;i<100;i++){w=advance(w);input+=w.air!.lastDay!.emitted;removed+=w.air!.lastDay!.removed;assert.equal(airTotals(w).load,input-removed);assert.ok(w.tiles.every(t=>Number.isInteger(t.air!.load)&&t.air!.load>=0));}let replay=initial;for(let i=0;i<100;i++)replay=advance(replay);assert.equal(stateHash(w),stateHash(replay));});
