import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createWorld} from '../packages/worldgen/src/index.js';import {advance,applyProposal,validateWorld} from '../packages/engine/src/index.js';import {ProposalSchema,type World,type Operation} from '../packages/contracts/src/index.js';import {DEFAULT_SETTLEMENT_SETTINGS} from '../packages/contracts/src/settlement-defaults.js';import {DEFAULT_DISEASE_SETTINGS} from '../packages/contracts/src/disease-defaults.js';import {journeyTotals} from '../packages/engine/src/journeys.js';import {healthTotals} from '../packages/engine/src/disease.js';import {armyJourneyPath} from '../packages/engine/src/armies.js';import {WorldStore,stateHash} from '../apps/server/src/store.js';import {forecast,PromptService} from '../apps/server/src/prompts.js';import {unpackBundle} from '../apps/server/src/portable.js';
const prop=(w:World,operations:Operation[])=>ProposalSchema.parse({id:`army-${w.revision}`,worldId:w.id,expectedRevision:w.revision,summary:'Troop movement',operations}),edit=(w:World,ops:Operation[])=>applyProposal(w,prop(w,ops));
function setup(){let w=createWorld({id:'armies',name:'Armies',seed:'armies',frequency:2});w.tiles.forEach(t=>t.elevationM=1000);const b=w.cells[0].neighbors[0],c=w.cells[b].neighbors.find(n=>n!==0&&!w.cells[0].neighbors.includes(n))!;w=edit(w,[{kind:'faction-define',tileId:0,expectedVersion:0,faction:{id:'oak',label:'Oak',color:'#336633'}},...[0,b,c].flatMap(tileId=>[{kind:'settlement-create' as const,tileId,label:'Village',population:100,foodRations:10000,settings:{...DEFAULT_SETTLEMENT_SETTINGS,growthPermille:0,lossPermille:0}},{kind:'rainfall' as const,tileId,mmPerDay:5},{kind:'temperature' as const,tileId,celsius:20,mode:'sustained' as const},{kind:'faction-claim' as const,tileId,factionId:'oak'}]),{kind:'garrison-configure',tileId:0,expectedVersion:0,target:60,reserveDays:7}]);return {w,b,c};}
const depart=(b:number,changes:Partial<Extract<Operation,{kind:'army-depart'}>>={}):Operation=>({kind:'army-depart',tileId:0,journeyId:'army',label:'Reinforcements',path:[0,b],daysPerHop:2,population:40,foodRations:400,...changes});

test('deployment debits healthy garrison, population and supplies exactly once; arrival reinforces',()=>{const {w,b}=setup(),before=journeyTotals(w);let n=edit(w,[depart(b)]);assert.equal(n.tiles[0].population,60);assert.equal(n.tiles[0].settlement!.foodRations,9600);assert.equal(n.tiles[0].garrison!.target,20);assert.equal(n.tiles[0].garrison!.version,2);assert.equal(n.journeys!.active[0].military!.factionId,'oak');assert.equal(journeyTotals(n).population,before.population);assert.equal(journeyTotals(n).foodRationsTotal,before.foodRationsTotal);n=advance(n);assert.equal(n.journeys!.active[0].foodRations,360);n=advance(n);assert.equal(n.journeys!.active.length,0);assert.equal(n.tiles[b].population,140);assert.equal(n.tiles[b].garrison!.target,40);assert.equal(n.tiles[b].garrison!.reserveDays,7);assert.equal(n.journeys!.lastDay!.entries[0].factionId,'oak');assert.equal(n.tiles[b].settlement!.lastDay!.consumed,140);assert.equal(advance(n).tiles[b].garrison!.target,40);assert.equal(journeyTotals(n).population,300);});

test('recruitment partitions only healthy residents, preserving all health totals even when health paused',()=>{let {w,b}=setup();w=edit(w,[{kind:'disease-configure',tileId:0,expectedVersion:0,enabled:false,settings:DEFAULT_DISEASE_SETTINGS},{kind:'disease-introduce',tileId:0,count:50},{kind:'disease-treat',tileId:0,count:30}]);const before=healthTotals(w),n=edit(w,[depart(b)]);assert.equal(n.journeys!.active[0].health!.ill,0);assert.equal(n.journeys!.active[0].health!.immune,15);assert.equal(n.tiles[0].health!.ill,20);assert.equal(n.tiles[0].health!.immune,15);assert.deepEqual(healthTotals(n),before);assert.deepEqual(healthTotals(advance(advance(n))),before);const ill=edit(w,[{kind:'disease-introduce',tileId:0,count:50}]);assert.throws(()=>edit(ill,[depart(b)]),/healthy/);});

test('insufficient staffing, journey provisions and home reserves reject atomically',()=>{const {w,b}=setup();for(const [changes,error] of [[{population:61},/healthy/],[{foodRations:79},/planned travel/],[{foodRations:9900},/remaining residents/]] as const){const hash=stateHash(w);assert.throws(()=>edit(w,[depart(b,changes)]),error);assert.equal(stateHash(w),hash);}assert.throws(()=>edit(edit(w,[{kind:'garrison-configure',tileId:0,expectedVersion:1,target:0,reserveDays:7}]),[depart(b)]),/healthy/);});

test('military identity limits paths to own/allied territory and delivery to own settlements',()=>{let {w,b,c}=setup();assert.deepEqual(armyJourneyPath(w,0,b),[0,b]);w=edit(w,[{kind:'faction-define',tileId:0,expectedVersion:1,faction:{id:'moon',label:'Moon',color:'#665599'}},{kind:'faction-claim',tileId:b,factionId:'moon'}]);assert.throws(()=>edit(w,[depart(c,{path:[0,b,c]})]),/own\/allied/);w=edit(w,[{kind:'faction-relation',tileId:0,expectedVersion:2,factionId:'oak',otherFactionId:'moon',relationship:'allied'}]);assert.deepEqual(armyJourneyPath(w,0,c),[0,b,c]);assert.ok(edit(w,[depart(c,{path:[0,b,c]})]).journeys!.active[0].military);assert.throws(()=>edit(w,[depart(b)]),/own-faction destination/);const unclaimed=edit(w,[{kind:'faction-claim',tileId:b,factionId:null}]);assert.throws(()=>armyJourneyPath(unclaimed,0,c),/No friendly/);});

test('changed ownership strands an army without allegiance change and blocks unloading/provisioning',()=>{let {w,b}=setup();w=edit(w,[depart(b),{kind:'faction-define',tileId:0,expectedVersion:1,faction:{id:'moon',label:'Moon',color:'#665599'}},{kind:'faction-claim',tileId:b,factionId:'moon'}]);const n=advance(w);assert.equal(n.journeys!.lastDay!.entries[0].status,'military-access');assert.equal(n.journeys!.active[0].remainingDays,2);assert.equal(n.journeys!.active[0].foodRations,360);assert.equal(n.journeys!.active[0].military!.factionId,'oak');let lost=edit(n,[{kind:'garrison-configure',tileId:0,expectedVersion:2,target:0,reserveDays:7},{kind:'faction-claim',tileId:0,factionId:'moon'}]);assert.throws(()=>edit(lost,[{kind:'journey-dock',tileId:0,journeyId:'army'}]),/military-access/);assert.throws(()=>edit(lost,[{kind:'journey-provision',tileId:0,journeyId:'army',foodRations:1}]),/allied/);lost=edit(lost,[{kind:'faction-claim',tileId:0,factionId:'oak'},{kind:'faction-claim',tileId:b,factionId:'oak'}]);assert.equal(advance(advance(lost)).tiles[b].population,140);});

test('dock/redirect/provision use existing ledger, restore service and preserve destination settings',()=>{let {w,b,c}=setup();w=edit(w,[depart(b)]);const before=journeyTotals(w);w=edit(w,[{kind:'journey-provision',tileId:0,journeyId:'army',foodRations:20}]);assert.equal(journeyTotals(w).foodRationsTotal,before.foodRationsTotal);const redirected=edit(w,[{kind:'journey-redirect',tileId:0,journeyId:'army',path:[0,b,c],daysPerHop:1},{kind:'garrison-configure',tileId:c,expectedVersion:0,target:10,reserveDays:2}]);const arrived=advance(advance(redirected));assert.equal(arrived.tiles[c].garrison!.target,50);assert.equal(arrived.tiles[c].garrison!.version,2);assert.equal(arrived.tiles[c].garrison!.reserveDays,2);w=edit(w,[{kind:'journey-dock',tileId:0,journeyId:'army'}]);assert.equal(w.tiles[0].population,100);assert.equal(w.tiles[0].garrison!.target,60);assert.equal(w.tiles[0].garrison!.version,3);assert.equal(w.journeys!.active.length,0);assert.equal(journeyTotals(w).foodRationsTotal,before.foodRationsTotal);});

test('capacity waits, health tracking and starvation retain exact population and health accounting',()=>{let {w,b}=setup();w=edit(w,[{kind:'settlement-configure',tileId:0,expectedRulesVersion:1,settings:{shortageIntervalDays:1,lossPermille:100}},{kind:'disease-configure',tileId:0,expectedVersion:0,enabled:true,settings:{...DEFAULT_DISEASE_SETTINGS,recoveryPermille:0,waterExposurePermille:0}},{kind:'settlement-configure',tileId:b,expectedRulesVersion:1,settings:{capacity:100}},depart(b,{foodRations:80})]);for(let i=0;i<5;i++)w=advance(w);assert.equal(w.journeys!.lastDay!.entries[0].status,'population-capacity');assert.ok(w.journeys!.active[0].population<40);assert.equal(healthTotals(w).population,journeyTotals(w).population);const survivors=w.journeys!.active[0].population;w=edit(w,[{kind:'settlement-configure',tileId:b,expectedRulesVersion:2,settings:{capacity:1000}}]);w=advance(w);assert.equal(w.tiles[b].garrison!.target,survivors);assert.equal(w.journeys!.active.length,0);validateWorld(w);});

test('army IDs share journey namespace; faction removal and malformed allegiance reject',()=>{let {w,b,c}=setup();w=edit(w,[depart(b,{population:60})]);assert.throws(()=>edit(w,[depart(b)]),/already been used/);const bad=structuredClone(w);bad.journeys!.active[0].military!.factionId='missing';assert.throws(()=>validateWorld(bad),/army faction/);w=edit(w,[...[0,b,c].map(tileId=>({kind:'faction-claim' as const,tileId,factionId:null}))]);assert.throws(()=>edit(w,[{kind:'faction-remove',tileId:0,expectedVersion:1,factionId:'oak'}]),/active armies/);const other=setup();assert.throws(()=>edit(other.w,[depart(other.b),{kind:'journey-depart',tileId:0,journeyId:'army',label:'Duplicate',path:[0,other.b],daysPerHop:1,population:1,foodRations:1,cargo:[]}]),/reused/);});

test('full path scope, pure previews and complete deterministic replay/checkpoint/export',async()=>{const root=await mkdtemp(join(tmpdir(),'logos-armies-')),store=new WorldStore(root);let {w,b}=setup();try{await store.save(w);const op=depart(b),hash=stateHash(w),f=forecast(w,prop(w,[op]));assert.equal(f.journeyPreview.applied.travelers,40);assert.equal(f.factionPreview!.garrisons.find(g=>g.tileId===b)!.target,40);assert.equal(stateHash(w),hash);for(const scope of ['tile','neighbors'] as const){const service=new PromptService(store,{name:'Army fixture',async generate(){return {kind:'proposal',message:'Army',assumptions:[],operations:[op]};}});try{await service.start(w,{id:scope,worldId:w.id,expectedRevision:w.revision,tileId:0,scope,mode:'propose',message:'Reinforce'});while(service.busy)await new Promise(r=>setTimeout(r,5));assert.equal((await service.get(w,scope)).status,scope==='tile'?'failed':'complete');}finally{await service.close();}}const p=prop(w,[op]);w=applyProposal(w,p);await store.save(w,{kind:'proposal',proposal:p});const transit=await store.checkpoint(w,'Army in transit');assert.equal(stateHash((await store.readCheckpoint(w.id,transit.id)).world),stateHash(w));assert.equal(stateHash((await unpackBundle(await store.exportBundle(w.id))).world),stateHash(w));let copy=structuredClone(w);for(let i=0;i<30;i++){w=advance(w);copy=advance(copy);}assert.equal(stateHash(w),stateHash(copy));await store.save(w,{kind:'step',days:30});assert.equal((await store.verifyHistory(w.id)).hash,stateHash(w));}finally{await rm(root,{recursive:true,force:true});}});
