import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {startServer} from '../dist/apps/server/src/index.js';import {WorldStore,stateHash} from '../dist/apps/server/src/store.js';import {createWorld} from '../dist/packages/worldgen/src/index.js';import {pngInfo} from '../dist/apps/server/src/artwork.js';
const root=await mkdtemp(join(tmpdir(),'logos-art-browser-')),store=new WorldStore(root),png=await readFile('packages/tile-packs/public/painterly-v1/alpine.png'),hash=pngInfo(png).hash,bundle={format:'logos-artwork',version:1,pack:{id:'stone-forest',version:1,label:'Stone forest',credit:'Original Logos alpine art',images:[{slot:'forest',hash}]},images:[{hash,data:png.toString('base64')}]};
for(const id of ['first-world','plain']){const w=createWorld({id,name:id==='plain'?'Plain world':'Artwork world',seed:'art-pack',frequency:2});w.tick=1000;w.revision=1000;for(const tile of w.tiles){tile.elevationM=500;tile.vegetation=.8;}await store.save(w);}
const original=stateHash(await store.load('first-world')),app=await startServer({root,port:0}),base=`http://127.0.0.1:${app.server.address().port}`,browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const pixels=page=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>{const gl=document.querySelector('#globe').getContext('webgl2'),data=new Uint8Array(200*200*4);gl.readPixels(Math.floor(gl.drawingBufferWidth/2)-100,Math.floor(gl.drawingBufferHeight/2)-100,200,200,gl.RGBA,gl.UNSIGNED_BYTE,data);let n=2166136261;for(let i=0;i<data.length;i++)n=Math.imul(n^data[i],16777619);resolve(n>>>0);})));
try{
 await mkdir('.local/screenshots',{recursive:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.waitForFunction(()=>document.querySelector('#art-status').textContent.includes('42 / 42'));const initialPixels=await pixels(page);
 await page.locator('#worlds-toggle').click();const upload=()=>page.locator('#import-artwork').setInputFiles({name:'stone-forest.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bundle))});await upload();await page.locator('#world-review').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#world-review-artwork img')?.naturalWidth>0);assert.match(await page.locator('#world-review-note').textContent(),/Stone forest v1/);assert.equal(stateHash(await store.load('first-world')),original);
 await page.screenshot({path:'.local/screenshots/artwork-pack-review.png'});await page.locator('#cancel-world-review').click();assert.equal(stateHash(await store.load('first-world')),original);await upload();await page.locator('#world-review').waitFor({state:'visible'});await page.locator('#apply-world-review').click();await page.locator('#world-review').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('#art-status').textContent.includes('42 / 42'));const importedPixels=await pixels(page);assert.notEqual(importedPixels,initialPixels);assert.equal((await store.load('first-world')).artwork.id,'stone-forest');
 await page.screenshot({path:'.local/screenshots/artwork-pack-world.png'});await page.reload();await page.waitForFunction(()=>document.querySelector('#art-status').textContent.includes('42 / 42'));assert.equal(await pixels(page),importedPixels);
 // A delayed old-world image must not overwrite the next world's atlas.
 let release;const gate=new Promise(resolve=>release=resolve);await page.route('**/api/artwork/image/**',async route=>{await gate;await route.fulfill({status:200,contentType:'image/png',body:png});});
 await page.reload();await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Saved locally'));await page.locator('#worlds-toggle').click();await page.getByRole('button',{name:'Plain world · day 1000',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#world-name').textContent==='Plain world');await page.waitForFunction(()=>document.querySelector('#art-status').textContent.includes('42 / 42'));release();await page.unrouteAll({behavior:'wait'});assert.equal(await pixels(page),initialPixels);
 await page.locator('#worlds-toggle').click();await page.getByRole('button',{name:'Artwork world · day 1000',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#world-name').textContent==='Artwork world');await page.waitForFunction(()=>document.querySelector('#art-status').textContent.includes('42 / 42'));assert.equal(await pixels(page),importedPixels);
 await page.locator('#worlds-toggle').click();assert.match(await page.locator('#world-artwork-status').textContent(),/Stone forest/);await page.locator('#reset-artwork').click();await page.locator('#world-review').waitFor({state:'visible'});await page.locator('#apply-world-review').click();await page.locator('#world-review').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('#art-status').textContent.includes('42 / 42'));assert.equal(await pixels(page),initialPixels);assert.equal((await store.load('first-world')).artwork,undefined);
 await page.locator('#worlds-toggle').click();await page.setViewportSize({width:390,height:844});await upload();await page.locator('#world-review').waitFor({state:'visible'});await page.screenshot({path:'.local/screenshots/artwork-pack-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#cancel-world-review').click();assert.deepEqual(errors,[]);
 console.log('Artwork browser passed: image review/cancel, no preview mutation, authenticated activation, GPU change, reload, delayed-image world-switch isolation, built-in reset and mobile review.');
}finally{await browser.close();await app.close();await rm(root,{recursive:true,force:true});}
