import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir, networkInterfaces } from 'node:os';
import { join } from 'node:path';
import { startServer } from '../dist/apps/server/src/index.js';
const root=await mkdtemp(join(tmpdir(),'logos-browser-'));
const app=await startServer({root,port:0,dev:process.env.LOGOS_BROWSER_DEV==='1'});
const address=app.server.address();
const lanAddress=Object.values(networkInterfaces()).flat().find(e=>e?.family==='IPv4'&&!e.internal)?.address;
if(process.env.LOGOS_BROWSER_LAN==='1'&&!lanAddress)throw Error('No LAN address available for test');
const base=`http://${process.env.LOGOS_BROWSER_LAN==='1'?lanAddress:'127.0.0.1'}:${address.port}`;
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(base);
 if(process.env.LOGOS_BROWSER_LAN==='1')assert.equal(await page.evaluate(()=>isSecureContext),false);
 await page.waitForFunction(()=>document.querySelector('#save-status')?.textContent?.includes('Saved locally'));
 await page.locator('#spin').click();
 await page.locator('#globe').click({position:{x:720,y:500}});
 await page.locator('#creator').waitFor({state:'visible'});
 await page.locator('#globe').focus();await page.keyboard.press('ArrowRight');
 await page.locator('#creator').waitFor({state:'visible'});
 await page.locator('#rain').fill('90');await page.locator('#rain-change').click();
 await page.locator('#proposal').waitFor({state:'visible'});
 const before=await page.locator('#day').textContent();
 await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});
 assert.equal(await page.locator('#day').textContent(),before);
 await page.locator('#step').click();
 await page.waitForFunction(before=>document.querySelector('#day')?.textContent!==before,before);
 await page.waitForFunction(()=>!document.body.classList.contains('busy'));
 const day=await page.locator('#day').textContent();
 await page.reload();await page.waitForFunction(()=>document.querySelector('#save-status')?.textContent?.includes('Saved locally'));
 assert.equal(await page.locator('#day').textContent(),day);
 await page.locator('#globe').focus();await page.keyboard.press('ArrowRight');
 await page.getByRole('button',{name:'Water',exact:true}).click();
 await mkdir('.local/screenshots',{recursive:true});
 await page.screenshot({path:'.local/screenshots/desktop.png'});
 await page.getByRole('button',{name:'Terrain',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);await page.screenshot({path:'.local/screenshots/mobile.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('#play').click();
 await page.waitForFunction(day=>document.querySelector('#day')?.textContent!==day,day);
 await page.locator('#play').click();
 const paused=await page.locator('#day').textContent();await page.waitForTimeout(1700);
 assert.equal(await page.locator('#day').textContent(),paused);
 await page.locator('#worlds-toggle').click();
 await page.locator('#new-name').fill('Browser world');await page.locator('#new-seed').fill('browser-seed');
 await page.getByRole('button',{name:'Create world',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#world-name')?.textContent==='Browser world');
 assert.equal(await page.locator('#day').textContent(),'DAY 0');
 assert.deepEqual(errors,[]);
 console.log('Browser smoke passed: selection, preview/apply, tick, reload, overlay, desktop/mobile, no page errors.');
}finally{await browser.close();await app.close();await rm(root,{recursive:true,force:true});}
