import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createWorld} from '../packages/worldgen/src/index.js';import {advance,applyProposal,validateWorld} from '../packages/engine/src/index.js';import {ProposalSchema,type World,type Operation} from '../packages/contracts/src/index.js';import {DEFAULT_SETTLEMENT_SETTINGS} from '../packages/contracts/src/settlement-defaults.js';import {DEFAULT_CONFLICT_SETTINGS} from '../packages/contracts/src/conflict.js';import {DEFAULT_DISEASE_SETTINGS} from '../packages/contracts/src/disease-defaults.js';import {journeyTotals} from '../packages/engine/src/journeys.js';import {healthTotals} from '../packages/engine/src/disease.js';import {resolveConflict,launchConflict} from '../packages/engine/src/conflict.js';import {reserveGarrisons,staffGarrisons} from '../packages/engine/src/garrisons.js';import {WorldStore,stateHash} from '../apps/server/src/store.js';import {forecast,PromptService} from '../apps/server/src/prompts.js';import {unpackBundle} from '../apps/server/src/portable.js';
const prop=(w:World,operations:Operation[])=>ProposalSchema.parse({id:`conflict-${w.revision}`,worldId:w.id,expectedRevision:w.revision,summary:'Conflict',operations}),edit=(w:World,ops:Operation[])=>applyProposal(w,prop(w,ops));
function setup(){let w=createWorld({id:'conflict',name:'Conflict',seed:'conflict',frequency:2});w.tiles.forEach(t=>t.elevationM=1000);const b=w.cells[0].neighbors[0];w=edit(w,[{kind:'faction-define',tileId:0,expectedVersion:0,faction:{id:'oak',label:'Oak',color:'#336633'}},{kind:'faction-define',tileId:0,expectedVersion:1,faction:{id:'moon',label:'Moon',color:'#665599'}},...[0,b].flatMap(tileId=>[{kind:'settlement-create' as const,tileId,label:'Village',population:tileId===0?200:100,foodRations:100000,settings:{...DEFAULT_SETTLEMENT_SETTINGS,farmRationsPerDay:1000,growthPermille:0,lossPermille:0}},{kind:'rainfall' as const,tileId,mmPerDay:5},{kind:'temperature' as const,tileId,celsius:20,mode:'sustained' as const},{kind:'faction-claim' as const,tileId,factionId:tileId===0?'oak':'moon'},{kind:'garrison-configure' as const,tileId,expectedVersion:0,target:tileId===0?120:30,reserveDays:7}]),{kind:'faction-relation',tileId:0,expectedVersion:2,factionId:'oak',otherFactionId:'moon',relationship:'hostile'}]);return {w,b};}
const configure=(w:World,enabled=true,settings:Partial<typeof DEFAULT_CONFLICT_SETTINGS>={}):Operation=>({kind:'conflict-configure',tileId:0,expectedVersion:w.conflict?.version??0,enabled,settings:{...DEFAULT_CONFLICT_SETTINGS,...settings}});

test('hostility alone stays inert; explicit policy launches real supplied troops after meals',()=>{let {w,b}=setup();assert.equal(advance(w).journeys,undefined);w=edit(w,[configure(w)]);const base=advance(edit(w,[configure(w,false)])),n=advance(w),j=n.journeys!.active[0];assert.equal(j.population,60);assert.equal(j.foodRations,420);assert.equal(j.military!.mission,'assault');assert.deepEqual(j.path,[0,b]);assert.equal(n.tiles[0].population,140);assert.equal(n.tiles[0].garrison!.target,60);assert.equal(journeyTotals(n).population,300);assert.equal(journeyTotals(n).foodRationsTotal,journeyTotals(base).foodRationsTotal);assert.equal(n.conflict!.lastDay!.launches.length,1);assert.equal(n.conflict!.lastDay!.battles.length,0);});

test('timed capture loses only combatants and survivors return without duplicating population',()=>{let {w,b}=setup();w=advance(edit(w,[configure(w)]));w=advance(w);assert.equal(w.conflict!.lastDay!.battles.length,0);w=advance(w);const battle=w.conflict!.lastDay!.battles[0];assert.equal(battle.outcome,'captured');assert.equal(battle.attackerLosses,3);assert.equal(battle.defenderLosses,3);assert.equal(w.tiles[b].factionId,'oak');assert.equal(w.tiles[b].population,97);assert.equal(w.tiles[b].garrison!.target,0);assert.equal(w.journeys!.active[0].population,57);assert.equal(w.journeys!.active[0].military!.mission,'return');assert.equal(w.journeys!.active[0].remainingDays,2);assert.equal(journeyTotals(w).population,294);w=advance(advance(w));assert.equal(w.journeys!.active.length,0);assert.equal(w.tiles[0].population,197);assert.equal(w.tiles[0].garrison!.target,117);assert.equal(journeyTotals(w).population,294);assert.equal(w.tiles[b].settlement!.label,'Village');});

test('civilian closures do not stop assaults or returns, and invasion changes no infrastructure/inventory',()=>{let {w,b}=setup();w=edit(w,[configure(w),{kind:'travel-permission',tileId:0,allowed:false},{kind:'travel-permission',tileId:b,allowed:false},{kind:'faction-borders-configure',tileId:0,expectedVersion:3,enabled:true,travel:true,trade:true,knowledge:true}]);w=advance(w);w.journeys!.active[0].remainingDays=0;reserveGarrisons(w);staffGarrisons(w);const before=structuredClone(w.tiles[b]);resolveConflict(w);const after=w.tiles[b];assert.equal(after.factionId,'oak');assert.equal(after.population,before.population-3);for(const key of ['settlement','properties','research','waterQuality','waterL','vegetation','elevationM','communication','travelAllowed'] as const)assert.deepEqual(after[key],before[key]);w=advance(advance(w));assert.equal(w.journeys!.active.length,0);assert.equal(w.tiles[0].population,197);});

test('reinforced defense can repel a previously justified attack; ties favor defenders',()=>{let {w,b}=setup();w=advance(edit(w,[configure(w)]));w=edit(w,[{kind:'garrison-configure',tileId:b,expectedVersion:1,target:60,reserveDays:7}]);w=advance(advance(w));const btl=w.conflict!.lastDay!.battles[0];assert.equal(btl.outcome,'repelled');assert.equal(btl.attackerAfter,54);assert.equal(btl.defenderAfter,54);assert.equal(w.tiles[b].factionId,'moon');assert.equal(w.tiles[b].population,94);assert.equal(w.tiles[b].garrison!.target,54);assert.equal(w.journeys!.active[0].military!.mission,'return');assert.equal(journeyTotals(w).population,288);});

test('pause or peace cancels pending assaults and recovers people/supplies at home',()=>{const {w}=setup();for(const peace of [false,true]){let n=advance(edit(w,[configure(w)]));n=edit(n,[peace?{kind:'faction-relation',tileId:0,expectedVersion:3,factionId:'oak',otherFactionId:'moon',relationship:'neutral'}:configure(n,false)]);n=advance(n);assert.equal(n.conflict!.lastDay!.battles[0].outcome,'cancelled');assert.equal(n.journeys!.active[0].military!.mission,'cancelled');assert.equal(journeyTotals(n).population,300);n=advance(n);assert.equal(n.journeys!.active.length,0);assert.equal(n.tiles[0].population,200);assert.equal(n.tiles[0].garrison!.target,120);}});

test('food, minimum force, advantage, global limits and cooldown prevent unbounded launches',()=>{const {w}=setup();for(const settings of [{minimumTroops:100},{deploymentPermille:0},{requiredAdvantagePermille:4000},{maxDeparturesPerDay:0}])assert.equal(advance(edit(w,[configure(w,true,settings)])).journeys?.active.length??0,0);let n=edit(w,[configure(w),{kind:'settlement-food',tileId:0,deltaRations:-99000}]);assert.equal(advance(n).conflict!.lastDay!.launches.some(l=>l.from===0),false);n=advance(edit(w,[configure(w)]));assert.equal(advance(n).conflict!.lastDay!.launches.length,0);n=advance(advance(advance(advance(n))));const target=n.cells[0].neighbors[0];n=edit(n,[{kind:'faction-claim',tileId:target,factionId:'moon'}]);assert.equal(advance(n).conflict!.lastDay!.launches.length,0);});

test('health-enabled and paused models lose healthy combatants only with exact compartment totals',()=>{for(const enabled of [false,true]){let {w,b}=setup();w=edit(w,[configure(w),{kind:'disease-configure',tileId:0,expectedVersion:0,enabled,settings:{...DEFAULT_DISEASE_SETTINGS,recoveryPermille:0,immunityLossPermille:0,waterExposurePermille:0}},{kind:'disease-introduce',tileId:b,count:90}]);for(let i=0;i<3;i++)w=advance(w);const battle=w.conflict!.lastDay!.battles[0];assert.equal(battle.defenderBefore,Math.min(enabled?10:30,10));assert.equal(battle.defenderLosses,1);assert.equal(w.tiles[b].health!.ill,90);assert.equal(healthTotals(w).ill,90);assert.equal(healthTotals(w).population,journeyTotals(w).population);assert.equal(healthTotals(w).population,300-battle.attackerLosses-battle.defenderLosses);validateWorld(w);}});

test('lost home ownership and arrival capacity strand returning survivors without changing allegiance',()=>{let {w}=setup();w=advance(advance(advance(edit(w,[configure(w)]))));const source=w.tiles[0];w=edit(w,[{kind:'garrison-configure',tileId:0,expectedVersion:source.garrison!.version,target:0,reserveDays:7},{kind:'faction-claim',tileId:0,factionId:'moon'}]);w=advance(advance(w));assert.equal(w.journeys!.lastDay!.entries[0].status,'military-access');assert.equal(w.journeys!.active[0].military!.factionId,'oak');w=edit(w,[{kind:'faction-claim',tileId:0,factionId:'oak'},{kind:'settlement-configure',tileId:0,expectedRulesVersion:1,settings:{capacity:140}}]);w=advance(w);assert.equal(w.journeys!.lastDay!.entries[0].status,'population-capacity');w=edit(w,[{kind:'settlement-configure',tileId:0,expectedRulesVersion:2,settings:{capacity:1000}}]);w=advance(w);assert.equal(w.journeys!.active.length,0);assert.equal(journeyTotals(w).population,294);});

test('settings, versions and malformed battle/campaign accounting reject',()=>{let {w}=setup();assert.throws(()=>edit(w,[configure(w,true,{provisionDays:4})]),/provisions/);const op=configure(w);w=edit(w,[op]);assert.throws(()=>edit(w,[op]),/Stale/);w=advance(advance(advance(w)));const bad=structuredClone(w);bad.conflict!.lastDay!.battles[0].attackerAfter++;assert.throws(()=>validateWorld(bad),/accounting/);const noPolicy=structuredClone(w);delete noPolicy.conflict;assert.throws(()=>validateWorld(noPolicy),/Campaigns/);});

test('world scope, five-day casualty preview, deterministic history, checkpoints and exports',async()=>{const root=await mkdtemp(join(tmpdir(),'logos-conflict-')),store=new WorldStore(root);let {w}=setup();try{await store.save(w);const op=configure(w),hash=stateHash(w),f=forecast(w,prop(w,[op]));assert.equal(f.conflictPreview!.forecastPopulation,294);assert.equal(f.conflictPreview!.baselinePopulation,300);assert.equal(f.conflictPreview!.days.flatMap(d=>d.battles)[0].outcome,'captured');assert.equal(stateHash(w),hash);for(const scope of ['tile','world'] as const){const service=new PromptService(store,{name:'Conflict fixture',async generate(){return {kind:'proposal',message:'Conflict',assumptions:[],operations:[op]};}});try{await service.start(w,{id:scope,worldId:w.id,expectedRevision:w.revision,tileId:0,scope,mode:'propose',message:'Conflict'});while(service.busy)await new Promise(r=>setTimeout(r,5));assert.equal((await service.get(w,scope)).status,scope==='world'?'complete':'failed');}finally{await service.close();}}const p=prop(w,[op]);w=applyProposal(w,p);await store.save(w,{kind:'proposal',proposal:p});let copy=structuredClone(w);for(let i=0;i<40;i++){w=advance(w);copy=advance(copy);}assert.equal(stateHash(w),stateHash(copy));await store.save(w,{kind:'step',days:40});assert.equal((await store.verifyHistory(w.id)).hash,stateHash(w));const cp=await store.checkpoint(w,'After conflict');assert.equal(stateHash((await store.readCheckpoint(w.id,cp.id)).world),stateHash(w));assert.equal(stateHash((await unpackBundle(await store.exportBundle(w.id))).world),stateHash(w));}finally{await rm(root,{recursive:true,force:true});}});

test('competing origins use one disjoint front in stable ID order',()=>{let {w,b}=setup();const c=w.cells[b].neighbors.find(id=>id!==0)!;w=edit(w,[{kind:'settlement-create',tileId:c,label:'Second camp',population:100,foodRations:100000,settings:{...DEFAULT_SETTLEMENT_SETTINGS,growthPermille:0,lossPermille:0}},{kind:'faction-claim',tileId:c,factionId:'oak'},{kind:'garrison-configure',tileId:c,expectedVersion:0,target:80,reserveDays:7},{kind:'rainfall',tileId:c,mmPerDay:5},{kind:'temperature',tileId:c,celsius:20,mode:'sustained'},configure(w)]);const reverse=structuredClone(w);for(const cell of reverse.cells)cell.neighbors.reverse();const a=advance(w),n=advance(reverse);assert.deepEqual(a.conflict!.lastDay,n.conflict!.lastDay);assert.equal(a.conflict!.lastDay!.launches.length,1);assert.equal(a.conflict!.lastDay!.launches[0].from,0);assert.equal(a.conflict!.lastDay!.launches[0].to,b);});

test('contact illness and visitors are excluded from defending casualties',()=>{let {w,b}=setup();w=edit(w,[configure(w),{kind:'disease-configure',tileId:0,expectedVersion:0,enabled:true,settings:{...DEFAULT_DISEASE_SETTINGS,recoveryPermille:0,immunityLossPermille:0,waterExposurePermille:0}},{kind:'disease-introduce',tileId:b,count:40},{kind:'disease-contact-configure',tileId:0,expectedVersion:1,enabled:true,ratePermille:100},{kind:'neighbor-visits-configure',tileId:0,expectedVersion:0,enabled:true,settings:{dailyPermille:1000,foodReserveDays:7,foodTargetDays:3,carryRationsPerVisitor:5}}]);w=advance(advance(w));const beforeIll=healthTotals(w).ill;w=advance(w);const report=w.conflict!.lastDay!.battles[0],out=w.neighborVisits!.lastDay!.entries.filter(e=>e.from===b),away=out.reduce((n,e)=>n+e.visitors,0),awayIll=out.reduce((n,e)=>n+(e.health?.ill??0),0);assert.ok(report.defenderBefore<=w.tiles[b].population+report.defenderLosses-away-(w.tiles[b].health!.ill-awayIll));assert.equal(healthTotals(w).ill,beforeIll+w.disease!.lastDay!.contactCases!);assert.equal(healthTotals(w).population,300-report.attackerLosses-report.defenderLosses);validateWorld(w);});
