import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createWorld} from '../packages/worldgen/src/index.js';import {advance,applyProposal,validateWorld} from '../packages/engine/src/index.js';import {advanceContacts,attachVisitHealth,healthTotals} from '../packages/engine/src/disease.js';import {DEFAULT_DISEASE_SETTINGS} from '../packages/contracts/src/disease-defaults.js';import {DEFAULT_SETTLEMENT_SETTINGS} from '../packages/contracts/src/settlement-defaults.js';import {DEFAULT_VISIT_SETTINGS} from '../packages/contracts/src/neighbor-visit-defaults.js';import {ProposalSchema,type World,type Operation} from '../packages/contracts/src/index.js';import {WorldStore,stateHash} from '../apps/server/src/store.js';import {PromptService,forecast} from '../apps/server/src/prompts.js';import {unpackBundle} from '../apps/server/src/portable.js';
const proposal=(w:World,ops:Operation[])=>ProposalSchema.parse({id:`contact-${w.revision}`,worldId:w.id,expectedRevision:w.revision,summary:'Contact changes',operations:ops}),edit=(w:World,ops:Operation[])=>applyProposal(w,proposal(w,ops));
const contact=(w:World,enabled=true,ratePermille=1000):Operation=>({kind:'disease-contact-configure',tileId:0,expectedVersion:w.disease!.version,enabled,ratePermille});
function setup(){let w=createWorld({id:'contacts',name:'Contacts',seed:'contacts',frequency:2});for(const t of w.tiles){t.elevationM=1000;t.temperatureC=20;t.rainMm=5;}const b=w.cells[0].neighbors[0],c=w.cells[b].neighbors.find(n=>n!==0)!;w=edit(w,[...[0,b,c].map(tileId=>({kind:'settlement-create' as const,tileId,label:'Village',population:100,foodRations:100000,settings:{...DEFAULT_SETTLEMENT_SETTINGS,growthPermille:0,lossPermille:0}})),{kind:'disease-configure',tileId:0,expectedVersion:0,enabled:true,settings:{...DEFAULT_DISEASE_SETTINGS,recoveryPermille:0,immunityLossPermille:0,waterExposurePermille:0}}]);return {w,b,c};}
function visits(w:World,edges:[number,number,number][]){w.neighborVisits={model:'neighbor-visits-v1',version:1,enabled:true,settings:{...DEFAULT_VISIT_SETTINGS},lastDay:{tick:w.tick,beforeFood:300000,afterFood:300000,entries:edges.map(([from,to,visitors])=>({from,to,visitors,purpose:'explore',rations:0}))}};}
test('contact activation is explicit/versioned, preserves settings on health pause, and old health ticks stay unchanged',()=>{let {w}=setup();w=edit(w,[{kind:'disease-introduce',tileId:0,count:40}]);const old=advance(w);assert.equal(old.tiles[0].health!.ill,40);assert.equal(old.disease!.contact,undefined);const op=contact(w);w=edit(w,[op]);assert.throws(()=>edit(w,[op]),/Stale/);const n=advance(w);assert.equal(n.tiles[0].health!.ill,64);assert.equal(n.disease!.lastDay!.contactCases,24);assert.equal(n.tiles[0].settlement!.lastDay!.illWorkers,64);assert.equal(healthTotals(n).population,300);const paused=edit(w,[{kind:'disease-configure',tileId:0,expectedVersion:w.disease!.version,enabled:false,settings:w.disease!.settings}]);assert.equal(paused.disease!.contact!.enabled,true);assert.equal(advance(paused).tiles[0].health!.ill,40);assert.equal(advance(edit(w,[contact(w,false)])).tiles[0].health!.ill,40);assert.equal(advance(edit(w,[contact(w,true,0)])).tiles[0].health!.ill,40);});
test('visitors acquire cases at destination and carry them home; immune people remain protected',()=>{let {w,b}=setup();w=edit(w,[contact(w),{kind:'disease-introduce',tileId:b,count:100}]);visits(w,[[0,b,50]]);attachVisitHealth(w);advanceContacts(w);assert.equal(w.tiles[0].health!.ill,33);assert.equal(w.neighborVisits!.lastDay!.entries[0].health!.ill,33);assert.equal(w.disease!.lastDay!.contactCases,33);assert.deepEqual(w.disease!.lastDay!.contactEntries![0],{group:'visitor',homeTileId:0,atTileId:b,population:50,susceptible:50,exposedToIll:100,presentPopulation:150,cases:33});validateWorld(w);
 let immune=setup().w;immune=edit(immune,[contact(immune),{kind:'disease-introduce',tileId:0,count:100},{kind:'disease-treat',tileId:0,count:60}]);advanceContacts(immune);assert.deepEqual(immune.tiles[0].health,{ill:40,immune:60});assert.equal(immune.disease!.lastDay!.contactCases,0);
});
test('frozen presence prevents cascades; empty destinations do not create residents; visit order cannot change outcome',()=>{let {w,b,c}=setup();w=edit(w,[contact(w),{kind:'disease-introduce',tileId:0,count:100}]);visits(w,[[0,b,50],[b,c,50]]);attachVisitHealth(w);const reversed=structuredClone(w);reversed.neighborVisits!.lastDay!.entries.reverse();advanceContacts(w);advanceContacts(reversed);assert.equal(w.tiles[b].health!.ill,25);assert.equal(w.tiles[c].health!.ill,0);assert.deepEqual(w.tiles.map(t=>t.health),reversed.tiles.map(t=>t.health));assert.equal(healthTotals(w).ill,125);validateWorld(w);
 const empty=w.cells[0].neighbors.find(n=>n!==b&&n!==c)!;let x=setup().w;x=edit(x,[contact(x),{kind:'disease-introduce',tileId:0,count:40}]);visits(x,[[0,empty,50]]);attachVisitHealth(x);advanceContacts(x);assert.equal(x.tiles[empty].population,0);assert.equal(x.tiles[empty].health!.ill,0);assert.equal(x.tiles[0].health!.ill,64);validateWorld(x);
});
test('transit parties mix internally; blocked parties do not expose destination and arrivals do',()=>{let {w,b}=setup();w=edit(w,[contact(w),{kind:'disease-introduce',tileId:0,count:40},{kind:'journey-depart',tileId:0,journeyId:'party',label:'Party',path:[0,b],population:50,foodRations:1000,daysPerHop:1,cargo:[]}]);const arrived=advance(w);assert.equal(arrived.journeys!.active.length,0);assert.equal(arrived.tiles[b].health!.ill,37);assert.equal(arrived.disease!.lastDay!.contactCases,29);let blocked=edit(w,[{kind:'travel-permission',tileId:b,allowed:false}]);blocked=advance(blocked);assert.equal(blocked.tiles[b].health!.ill,0);assert.equal(blocked.journeys!.active[0].health!.ill,32);assert.equal(blocked.disease!.lastDay!.contactEntries!.find(e=>e.group==='transit')!.cases,12);assert.equal(healthTotals(blocked).population,300);});
test('actual travel closures suppress cross-zone contact; tiny groups remain bounded over long replay',()=>{let {w,b}=setup();w=edit(w,[contact(w),{kind:'disease-introduce',tileId:0,count:100},{kind:'neighbor-visits-configure',tileId:0,expectedVersion:0,enabled:true,settings:{...DEFAULT_VISIT_SETTINGS,dailyPermille:500}},{kind:'travel-permission',tileId:0,allowed:false}]);const closed=advance(w);assert.equal(closed.tiles[b].health!.ill,0);assert.equal(closed.neighborVisits!.lastDay!.entries.some(e=>e.from===0||e.to===0),false);let a=edit(w,[{kind:'travel-permission',tileId:0,allowed:true}]),copy=structuredClone(a);for(let i=0;i<100;i++){a=advance(a);copy=advance(copy);assert.equal(healthTotals(a).population,300);}assert.equal(stateHash(a),stateHash(copy));assert.ok(healthTotals(a).ill>100);
 let tiny=setup().w;tiny=edit(tiny,[contact(tiny,true,1),{kind:'disease-introduce',tileId:0,count:1}]);assert.equal(advance(tiny).disease!.lastDay!.contactCases,0);const bad=structuredClone(a);bad.disease!.lastDay!.contactCases=999999;assert.throws(()=>validateWorld(bad),/balance/);
});
test('contact proposals enforce world scope, forecasts do not mutate saves, and history/checkpoints/portable preserve contact state',async()=>{const root=await mkdtemp(join(tmpdir(),'logos-contact-')),store=new WorldStore(root);let {w}=setup();try{await store.save(w);const hash=stateHash(w),op=contact(w);assert.ok(forecast(w,proposal(w,[op])).healthPreview);assert.equal(stateHash(w),hash);for(const scope of ['tile','world'] as const){const service=new PromptService(store,{name:'contact fixture',async generate(){return {kind:'proposal',message:'Contacts',assumptions:[],operations:[op]};}});try{await service.start(w,{id:scope,worldId:w.id,expectedRevision:w.revision,tileId:0,scope,mode:'propose',message:'Enable contacts'});while(service.busy)await new Promise(r=>setTimeout(r,5));assert.equal((await service.get(w,scope)).status,scope==='world'?'complete':'failed');}finally{await service.close();}}
 const p=proposal(w,[op,{kind:'disease-introduce',tileId:0,count:40}]);w=applyProposal(w,p);await store.save(w,{kind:'proposal',proposal:p});for(let i=0;i<30;i++)w=advance(w);await store.save(w,{kind:'step',days:30});assert.equal((await store.verifyHistory(w.id)).hash,stateHash(w));const cp=await store.checkpoint(w,'Contacts');assert.equal(stateHash((await store.readCheckpoint(w.id,cp.id)).world),stateHash(w));assert.equal(stateHash((await unpackBundle(await store.exportBundle(w.id))).world),stateHash(w));}finally{await rm(root,{recursive:true,force:true});}});

test('contact cases remain valid through same-day starvation and large population edits',()=>{let {w}=setup();w=edit(w,[contact(w),{kind:'disease-introduce',tileId:0,count:40},{kind:'settlement-food',tileId:0,deltaRations:-100000},{kind:'settlement-configure',tileId:0,expectedRulesVersion:1,settings:{farmRationsPerDay:0,shortageIntervalDays:1,lossPermille:500}}]);const n=advance(w);assert.equal(n.disease!.lastDay!.contactCases,24);assert.equal(n.tiles[0].population,50);assert.equal(n.tiles[0].health!.ill,32);validateWorld(n);
 let large=setup().w;large=edit(large,[contact(large),{kind:'settlement-configure',tileId:0,expectedRulesVersion:1,settings:{capacity:1000000}},{kind:'settlement-population',tileId:0,population:1000000},{kind:'disease-introduce',tileId:0,count:400000}]);advanceContacts(large);assert.equal(large.disease!.lastDay!.contactCases,240000);assert.equal(large.tiles[0].health!.ill,640000);validateWorld(large);
});
