import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdtemp,rm,mkdir,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {WorldStore,stateHash} from '../dist/apps/server/src/store.js';import {createWorld} from '../dist/packages/worldgen/src/index.js';import {startServer} from '../dist/apps/server/src/index.js';import {applyProposal} from '../dist/packages/engine/src/index.js';import {DEFAULT_SETTLEMENT_SETTINGS} from '../dist/packages/contracts/src/settlement-defaults.js';
const root=await mkdtemp(join(tmpdir(),'logos-ecology-browser-')),store=new WorldStore(root);let world=createWorld({id:'first-world',name:'Soil garden',seed:'soil-browser',frequency:2});world.tiles.forEach(t=>t.elevationM=1000);world.rules=[{id:'rain-0',kind:'rainfall',tileId:0,mmPerDay:5},{id:'temperature-0',kind:'temperature',tileId:0,celsius:20}];
const sample=JSON.parse(await readFile('docs/examples/soil-fertility.json','utf8'));world=applyProposal(world,{id:'setup',worldId:world.id,expectedRevision:0,summary:'Soil garden',operations:[...sample.operations,{kind:'settlement-create',tileId:0,label:'City',population:50000,foodRations:10000000,settings:{...DEFAULT_SETTLEMENT_SETTINGS,capacity:100000,farmRationsPerDay:100000}}]});await store.save(world);let calls=0;
const app=await startServer({root,port:0,provider:{name:'Soil fixture',async generate(){calls++;return {kind:'proposal',message:'Reduce to a farming community of 1000 inhabitants.',assumptions:[],operations:[{kind:'settlement-population',tileId:0,population:1000}]};}}}),base=`http://127.0.0.1:${app.server.address().port}`,browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{await mkdir('.local/screenshots',{recursive:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Saved locally'));await page.locator('#globe').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowLeft');await page.locator('#settlement-controls summary').click();
 const before=stateHash(await store.load(world.id));await page.locator('#soil-enable').click();await page.locator('#proposal').waitFor({state:'visible'});assert.match(await page.locator('#preview-results').textContent(),/soil ecology for the entire world/);assert.match(await page.locator('#preview-results').textContent(),/paused/);assert.equal(stateHash(await store.load(world.id)),before);await page.locator('#cancel-proposal').click();assert.equal(stateHash(await store.load(world.id)),before);
 await page.locator('#soil-enable').click();await page.locator('#proposal').waitFor({state:'visible'});await page.screenshot({path:'.local/screenshots/ecology-review.png'});await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});let saved=await store.load(world.id);assert.ok(saved.soilEcology.enabled);assert.equal(saved.tiles[0].properties['soil-fertility']??50,50);assert.equal(saved.definitions.rules.filter(r=>r.enabled).length,0);
 const step=async day=>{await page.locator('#step').click();await page.waitForFunction(n=>document.querySelector('#day').textContent===`DAY ${n}`,day);};await step(1);saved=await store.load(world.id);assert.equal(saved.tiles[0].properties['soil-fertility'],49.2);assert.equal(saved.tiles[0].settlement.lastDay.produced,49200);assert.match(await page.locator('.soil-ledger').textContent(),/urban pressure −1.000/);assert.match(await page.locator('.settlement-ledger').textContent(),/49.2% soil fertility/);
 await page.locator('#chat-open').click();await page.locator('#chat-message').fill('Reduce this city to 1000 inhabitants.');await page.locator('#chat-propose').click();await page.locator('#chat-progress').waitFor({state:'hidden'});await page.getByRole('button',{name:'Review five-day preview'}).click();await page.locator('#proposal').waitFor({state:'visible'});await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});await page.locator('#chat-close').click();await step(2);assert.match(await page.locator('.soil-ledger').textContent(),/farmer stewardship \+0.500/);assert.equal((await store.load(world.id)).tiles[0].properties['soil-fertility'],49.9);
 await page.locator('#custom-layer').selectOption('custom:soil-fertility');await page.locator('.soil-ledger').scrollIntoViewIfNeeded();await page.screenshot({path:'.local/screenshots/ecology-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('.soil-ledger').scrollIntoViewIfNeeded();await page.screenshot({path:'.local/screenshots/ecology-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const hash=stateHash(await store.load(world.id));await page.reload();await page.waitForFunction(()=>document.querySelector('#day').textContent==='DAY 2');assert.equal(stateHash(await store.load(world.id)),hash);assert.equal((await store.verifyHistory(world.id)).hash,hash);assert.equal(calls,1);assert.deepEqual(errors,[]);console.log('Ecology browser passed: reviewed activation/cancel, preserved soil and explicit writer disabling, city losses, soil-limited harvest, prompted farmer transition, overlay, reload/replay, desktop/mobile, no autonomous models.');
}finally{await browser.close();await app.close();await rm(root,{recursive:true,force:true});}
