import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {WorldStore,stateHash} from '../dist/apps/server/src/store.js';import {createWorld} from '../dist/packages/worldgen/src/index.js';import {startServer} from '../dist/apps/server/src/index.js';
const example=JSON.parse(await readFile('docs/examples/rain-cistern.json','utf8')),root=await mkdtemp(join(tmpdir(),'logos-entity-browser-')),store=new WorldStore(root),world=createWorld({id:'first-world',name:'Cistern garden',seed:'cisterns',frequency:2});await store.save(world);let calls=0;
const app=await startServer({root,port:0,provider:{name:'Entity fixture',async generate(context){calls++;assert.ok(context.capabilities.operations['entity-create']);if(calls===1)return {kind:'proposal',message:'Build a rain cistern with a tracked supply index.',assumptions:['Stored rain is an abstract index; physical runoff is unchanged.'],operations:example.operations};return {kind:'proposal',message:'Reduce cistern capacity to 15 with explicit clamping.',assumptions:[],operations:[{...example.operations[0],migration:'clamp',definition:{...example.operations[0].definition,version:2,properties:[{...example.operations[0].definition.properties[0],max:15}]}},...example.operations.filter(o=>o.kind==='rule-define').map(o=>({...o,rule:{...o.rule,version:2}}))]};}}}),base=`http://127.0.0.1:${app.server.address().port}`,browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 await mkdir('.local/screenshots',{recursive:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Saved locally'));await page.locator('#globe').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowLeft');
 const request=async message=>{await page.locator('#chat-open').click();await page.locator('#chat-scope').selectOption('world');await page.locator('#chat-message').fill(message);await page.locator('#chat-propose').click();await page.locator('#chat-progress').waitFor({state:'hidden'});await page.getByRole('button',{name:'Review five-day preview'}).first().click();await page.locator('#proposal').waitFor({state:'visible'});};
 await request('Create a rain cistern here and show its collected rain.');await page.locator('.entity-preview summary').click();assert.match(await page.locator('.entity-preview').textContent(),/Stored rain 50 rain units/);assert.equal(stateHash(await store.load(world.id)),stateHash(world));await page.screenshot({path:'.local/screenshots/entities-preview.png'});await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});await page.locator('#chat-close').click();assert.match(await page.locator('.entity-note').textContent(),/Stored rain: 0 rain units/);
 for(let day=1;day<=2;day++){await page.locator('#step').click();await page.waitForFunction(n=>document.querySelector('#day').textContent===`DAY ${n}`,day);}assert.match(await page.locator('.entity-note').textContent(),/Stored rain: 20 rain units/);assert.equal((await store.load(world.id)).tiles[0].properties['cistern-supply'],10);
 await page.reload();await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Saved locally'));await page.locator('#globe').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowLeft');assert.match(await page.locator('.entity-note').textContent(),/Stored rain: 20 rain units/);
 await request('Reduce capacity to 15 and clamp stored rain.');await page.locator('.entity-preview summary').click();assert.match(await page.locator('.entity-preview').textContent(),/Stored rain 15 rain units/);assert.equal((await store.load(world.id)).entities.instances[0].properties.stored,20);await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});await page.locator('#chat-close').click();assert.match(await page.locator('.entity-note').textContent(),/Stored rain: 15 rain units/);await page.screenshot({path:'.local/screenshots/entities-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/screenshots/entities-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(calls,2);assert.deepEqual(errors,[]);
 console.log('Entity browser passed: prompted building creation, readable Apply/day+5 preview without writes, deterministic collection/supply, reload/inspection, reviewed clamp migration, mobile, and no autonomous model calls.');
}finally{await browser.close();await app.close();await rm(root,{recursive:true,force:true});}
