import {modelSchema} from '../packages/contracts/src/model-schema.js';import {factionOperations} from '../packages/contracts/src/factions.js';
import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createWorld} from '../packages/worldgen/src/index.js';import {advance,applyProposal,validateWorld} from '../packages/engine/src/index.js';import {appearance} from '../packages/globe/src/appearance.js';import {DEFAULT_SETTLEMENT_SETTINGS} from '../packages/contracts/src/settlement-defaults.js';import {ProposalSchema,type World,type Operation} from '../packages/contracts/src/index.js';import {WorldStore,stateHash} from '../apps/server/src/store.js';import {forecast,PromptService} from '../apps/server/src/prompts.js';import {unpackBundle} from '../apps/server/src/portable.js';
const prop=(w:World,operations:Operation[])=>ProposalSchema.parse({id:`factions-${w.revision}`,worldId:w.id,expectedRevision:w.revision,summary:'Faction change',operations}),edit=(w:World,ops:Operation[])=>applyProposal(w,prop(w,ops));
const define=(w:World,id='oak'):Operation=>({kind:'faction-define',tileId:0,expectedVersion:w.factions?.version??0,faction:{id,label:id==='oak'?'Oak Circle':'Moon Court',color:id==='oak'?'#336633':'#665599'}});
function setup(){let w=createWorld({id:'factions',name:'Factions',seed:'factions',frequency:2});w.tiles.forEach(t=>t.elevationM=1000);w=edit(w,[{kind:'settlement-create',tileId:0,label:'Village',population:100,foodRations:10000,settings:{...DEFAULT_SETTLEMENT_SETTINGS,growthPermille:0,lossPermille:0}}]);return w;}
test('definitions initialize explicitly and rename/recolor preserve identity and territory',()=>{let w=setup();assert.equal(advance(w).factions,undefined);const op=define(w);w=edit(w,[op,{kind:'faction-claim',tileId:0,factionId:'oak'}]);assert.equal(w.factions!.version,1);assert.equal(w.tiles[0].factionId,'oak');assert.equal(appearance(w,w.tiles[0],'territory').color,'#336633');assert.throws(()=>edit(w,[op]),/Stale/);w=edit(w,[{kind:'faction-define',tileId:0,expectedVersion:1,faction:{id:'oak',label:'Oak Realm',color:'#abcdef'}}]);assert.equal(w.factions!.definitions.length,1);assert.equal(w.tiles[0].factionId,'oak');assert.equal(appearance(w,w.tiles[0],'territory').color,'#abcdef');});
test('claims replace only ownership, reject new sea claims and survive later submergence/depopulation',()=>{let w=setup();const before=structuredClone(w.tiles[0]);w=edit(w,[define(w),{kind:'faction-claim',tileId:0,factionId:'oak'}]);const {factionId,...after}=w.tiles[0];assert.deepEqual(after,before);w=edit(w,[define(w,'moon'),{kind:'faction-claim',tileId:0,factionId:'moon'}]);assert.equal(w.tiles[0].factionId,'moon');w=edit(w,[{kind:'elevation',tileId:0,deltaM:-1500},{kind:'settlement-population',tileId:0,population:0}]);assert.equal(advance(w).tiles[0].factionId,'moon');assert.throws(()=>edit(w,[{kind:'faction-claim',tileId:0,factionId:'oak'}]),/land/);w=edit(w,[{kind:'faction-claim',tileId:0,factionId:null}]);assert.equal(w.tiles[0].factionId,undefined);assert.throws(()=>edit(w,[{kind:'faction-claim',tileId:1,factionId:'missing'}]),/Define/);});
test('relations normalize symmetric pairs, neutral clears them, removal requires unclaimed territory',()=>{let w=setup();w=edit(w,[define(w)]);w=edit(w,[define(w,'moon'),{kind:'faction-claim',tileId:0,factionId:'oak'}]);w=edit(w,[{kind:'faction-relation',tileId:0,expectedVersion:2,factionId:'oak',otherFactionId:'moon',relationship:'hostile'}]);assert.deepEqual(w.factions!.relations,[{a:'moon',b:'oak',relationship:'hostile'}]);assert.throws(()=>edit(w,[{kind:'faction-remove',tileId:0,expectedVersion:3,factionId:'oak'}]),/territory/);assert.throws(()=>edit(w,[{kind:'faction-relation',tileId:0,expectedVersion:3,factionId:'oak',otherFactionId:'oak',relationship:'allied'}]),/distinct/);w=edit(w,[{kind:'faction-relation',tileId:0,expectedVersion:3,factionId:'moon',otherFactionId:'oak',relationship:'neutral'}]);assert.equal(w.factions!.relations.length,0);w=edit(w,[{kind:'faction-relation',tileId:0,expectedVersion:4,factionId:'moon',otherFactionId:'oak',relationship:'allied'}]);w=edit(w,[{kind:'faction-claim',tileId:0,factionId:null},{kind:'faction-remove',tileId:0,expectedVersion:5,factionId:'oak'}]);assert.equal(w.factions!.definitions.length,1);assert.equal(w.factions!.relations.length,0);});
test('invalid ownership, duplicate relationships and registry limits reject atomically',()=>{let w=setup();w=edit(w,[define(w)]);const bad=structuredClone(w);bad.tiles[0].factionId='missing';assert.throws(()=>validateWorld(bad),/owner/);w=edit(w,[define(w,'moon')]);const pair={a:'moon',b:'oak',relationship:'allied' as const};const duplicate=structuredClone(w);duplicate.factions!.relations=[pair,pair];assert.throws(()=>validateWorld(duplicate),/relationship/);for(let i=0;i<30;i++)w=edit(w,[define(w,`f-${i}`)]);const hash=stateHash(w);assert.throws(()=>edit(w,[define(w,'overflow')]));assert.equal(stateHash(w),hash);});
test('territory and hostile labels do not change deterministic physics, population or movement permissions',()=>{let legacy=setup(),w=edit(legacy,[define(legacy),{kind:'faction-claim',tileId:0,factionId:'oak'}]);w=edit(w,[define(w,'moon')]);w=edit(w,[{kind:'faction-relation',tileId:0,expectedVersion:2,factionId:'oak',otherFactionId:'moon',relationship:'hostile'}]);for(let i=0;i<50;i++){w=advance(w);legacy=advance(legacy);assert.deepEqual(w.tiles.map(({factionId,...t})=>t),legacy.tiles);}assert.equal(w.tiles[0].travelAllowed,undefined);assert.equal(w.tiles[0].communication,legacy.tiles[0].communication);});
test('world-only registry scope, local claim scope, pure forecasts and complete replay/checkpoint/portable state',async()=>{const root=await mkdtemp(join(tmpdir(),'logos-factions-')),store=new WorldStore(root);let w=setup();try{w=edit(w,[define(w)]);await store.save(w);const hash=stateHash(w);assert.equal(forecast(w,prop(w,[{kind:'faction-claim',tileId:0,factionId:'oak'}])).factionPreview!.applied[0].zones,1);assert.equal(stateHash(w),hash);for(const [id,scope,op,status] of [['registry-tile','tile',define(w,'moon'),'failed'],['registry-world','world',define(w,'moon'),'complete'],['claim-local','tile',{kind:'faction-claim',tileId:0,factionId:'oak'},'complete'],['claim-outside','tile',{kind:'faction-claim',tileId:1,factionId:'oak'},'failed']] as const){const service=new PromptService(store,{name:'Faction fixture',async generate(){return {kind:'proposal',message:'Faction',assumptions:[],operations:[op]};}});try{await service.start(w,{id,worldId:w.id,expectedRevision:w.revision,tileId:0,scope,mode:'propose',message:'Factions'});while(service.busy)await new Promise(r=>setTimeout(r,5));assert.equal((await service.get(w,id)).status,status);}finally{await service.close();}}
 const p=prop(w,[{kind:'faction-claim',tileId:0,factionId:'oak'}]);w=applyProposal(w,p);await store.save(w,{kind:'proposal',proposal:p});for(let i=0;i<30;i++)w=advance(w);await store.save(w,{kind:'step',days:30});assert.equal((await store.verifyHistory(w.id)).hash,stateHash(w));const cp=await store.checkpoint(w,'Territory');assert.equal(stateHash((await store.readCheckpoint(w.id,cp.id)).world),stateHash(w));assert.equal(stateHash((await unpackBundle(await store.exportBundle(w.id))).world),stateHash(w));}finally{await rm(root,{recursive:true,force:true});}});

test('model response schema represents required nullable ownership for release proposals',()=>{const schema=modelSchema(factionOperations[2]) as {required:string[];properties:{factionId:{anyOf:unknown[]}}};assert.ok(schema.required.includes('factionId'));assert.deepEqual(schema.properties.factionId.anyOf[1],{type:'null'});assert.equal(factionOperations[2].parse({kind:'faction-claim',tileId:0,factionId:null}).factionId,null);assert.throws(()=>factionOperations[2].parse({kind:'faction-claim',tileId:0}));});
