import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createWorld} from '../packages/worldgen/src/index.js';import {advance,applyProposal} from '../packages/engine/src/index.js';import {ProposalSchema,type World,type Operation} from '../packages/contracts/src/index.js';import {DEFAULT_SETTLEMENT_SETTINGS} from '../packages/contracts/src/settlement-defaults.js';import {DEFAULT_FOOD_TRADE_SETTINGS} from '../packages/contracts/src/food-trade-defaults.js';import {DEFAULT_MIGRATION_SETTINGS} from '../packages/contracts/src/migration-defaults.js';import {DEFAULT_VISIT_SETTINGS} from '../packages/contracts/src/neighbor-visit-defaults.js';import {DEFAULT_RESEARCH_SETTINGS,CULTIVATION_TECHNOLOGY} from '../packages/contracts/src/technology.js';
import {factionBorderOpen} from '../packages/engine/src/factions.js';import {landJourneyPath} from '../packages/engine/src/journey-path.js';import {advanceJourneys,journeyTotals} from '../packages/engine/src/journeys.js';import {advanceNeighborVisits} from '../packages/engine/src/neighbor-visits.js';import {advanceMigration} from '../packages/engine/src/migration.js';import {advanceFoodTrade} from '../packages/engine/src/food-trade.js';import {WorldStore,stateHash} from '../apps/server/src/store.js';import {forecast,PromptService} from '../apps/server/src/prompts.js';import {unpackBundle} from '../apps/server/src/portable.js';
const prop=(w:World,operations:Operation[])=>ProposalSchema.parse({id:`borders-${w.revision}`,worldId:w.id,expectedRevision:w.revision,summary:'Border policy',operations});const edit=(w:World,ops:Operation[])=>applyProposal(w,prop(w,ops));
const policy=(w:World,flags:Partial<{enabled:boolean;travel:boolean;trade:boolean;knowledge:boolean}>={}):Operation=>({kind:'faction-borders-configure',tileId:0,expectedVersion:w.factions!.version,enabled:true,travel:true,trade:true,knowledge:true,...flags});
function setup(){let w=createWorld({id:'borders',name:'Borders',seed:'borders',frequency:2});w.tiles.forEach(t=>t.elevationM=1000);const b=w.cells[0].neighbors[0];w=edit(w,[...[0,b].flatMap(tileId=>[{kind:'settlement-create' as const,tileId,label:'Village',population:100,foodRations:10000,settings:{...DEFAULT_SETTLEMENT_SETTINGS,growthPermille:0,lossPermille:0}},{kind:'rainfall' as const,tileId,mmPerDay:5},{kind:'temperature' as const,tileId,celsius:20,mode:'sustained' as const}]),{kind:'faction-define',tileId:0,expectedVersion:0,faction:{id:'oak',label:'Oak',color:'#336633'}},{kind:'faction-define',tileId:0,expectedVersion:1,faction:{id:'moon',label:'Moon',color:'#665599'}},{kind:'faction-claim',tileId:0,factionId:'oak'},{kind:'faction-claim',tileId:b,factionId:'moon'},{kind:'faction-relation',tileId:0,expectedVersion:2,factionId:'moon',otherFactionId:'oak',relationship:'hostile'}]);return {w,b};}
const depart=(b:number,cargo:{fieldId:string;amount:number}[]=[]):Operation=>({kind:'journey-depart',tileId:0,journeyId:'party',label:'Travelers',path:[0,b],daysPerHop:2,population:10,foodRations:100,cargo});
const stock:Operation={kind:'field-define',tileId:0,migration:'preserve',definition:{id:'mana',version:1,label:'Mana',unit:'motes',description:'',quantity:'stock',min:0,max:100,defaultValue:0}};

test('explicit optional borders are symmetric, channel-specific and keep ordinary permissions',()=>{const {w,b}=setup();assert.equal(factionBorderOpen(w,0,b,'travel'),true);for(const channel of ['travel','trade','knowledge'] as const){const n=edit(w,[policy(w,{travel:false,trade:false,knowledge:false,[channel]:true})]);for(const c of ['travel','trade','knowledge'] as const){assert.equal(factionBorderOpen(n,0,b,c),c!==channel);assert.equal(factionBorderOpen(n,b,0,c),c!==channel);}assert.equal(factionBorderOpen(n,0,0,channel),true);const paused=edit(n,[policy(n,{enabled:false})]);assert.equal(factionBorderOpen(paused,0,b,channel),true);}
 const blocked=edit(w,[policy(w)]);for(const relationship of ['neutral','allied'] as const){const n=edit(blocked,[{kind:'faction-relation',tileId:0,expectedVersion:blocked.factions!.version,factionId:'oak',otherFactionId:'moon',relationship}]);assert.equal(factionBorderOpen(n,0,b,'travel'),true);}for(const factionId of ['oak',null])assert.equal(factionBorderOpen(edit(blocked,[{kind:'faction-claim',tileId:b,factionId}]),0,b,'travel'),true);const closed=edit(blocked,[policy(blocked,{enabled:false}),{kind:'travel-permission',tileId:b,allowed:false}]);assert.throws(()=>landJourneyPath(closed,0,b),/Endpoints/);});

test('pathfinding avoids hostile edges and no path/departure rejection is atomic',()=>{const {w,b}=setup(),n=edit(w,[policy(w)]);const path=landJourneyPath(n,0,b);assert.ok(path.length>2);for(let i=1;i<path.length;i++)assert.ok(factionBorderOpen(n,path[i-1],path[i],'travel'));const hash=stateHash(n);assert.throws(()=>edit(n,[depart(b)]),/faction border/);assert.equal(stateHash(n),hash);const isolated=edit(n,w.cells[0].neighbors.filter(id=>id!==b).map(tileId=>({kind:'travel-permission',tileId,allowed:false})));assert.throws(()=>landJourneyPath(isolated,0,b),/No open land path/);});

test('in-flight closure freezes the leg and accounts food; reopening resumes exactly once',()=>{let {w,b}=setup();w=edit(w,[depart(b)]);w=advance(w);assert.equal(w.journeys!.active[0].remainingDays,1);w=edit(w,[policy(w)]);const total=journeyTotals(w).population,food=w.journeys!.active[0].foodRations;w=advance(w);assert.equal(w.journeys!.lastDay!.entries[0].status,'border-closed');assert.equal(w.journeys!.active[0].remainingDays,1);assert.equal(w.journeys!.active[0].foodRations,food-10);assert.equal(journeyTotals(w).population,total);w=edit(w,[policy(w,{enabled:false})]);w=advance(w);assert.equal(w.journeys!.active.length,0);assert.equal(w.tiles[b].population,110);assert.equal(journeyTotals(w).population,total);assert.equal(advance(w).tiles[b].population,110);});

test('stranded parties can provision, redirect or dock locally without crossing a border',()=>{let {w,b}=setup();w=edit(w,[depart(b),policy(w)]);const initial=journeyTotals(w);w=edit(w,[{kind:'journey-provision',tileId:0,journeyId:'party',foodRations:20}]);assert.equal(journeyTotals(w).foodRationsTotal,initial.foodRationsTotal);const path=landJourneyPath(w,0,b);const redirected=edit(w,[{kind:'journey-redirect',tileId:0,journeyId:'party',path,daysPerHop:1}]);assert.deepEqual(redirected.journeys!.active[0].path,path);const docked=edit(w,[{kind:'journey-dock',tileId:0,journeyId:'party'}]);assert.equal(docked.journeys!.active.length,0);assert.equal(docked.tiles[0].population,100);assert.equal(journeyTotals(docked).foodRationsTotal,initial.foodRationsTotal);});

test('trade blocks stock cargo but personal journey provisions are exempt',()=>{let {w,b}=setup();w=edit(w,[stock,{kind:'field-set',tileId:0,fieldId:'mana',value:60},policy(w,{travel:false})]);assert.throws(()=>edit(w,[depart(b,[{fieldId:'mana',amount:10}])]),/trade border/);assert.equal(edit(w,[depart(b)]).journeys!.active.length,1);let open=edit(w,[policy(w,{enabled:false})]);open=edit(open,[depart(b,[{fieldId:'mana',amount:10}])]);open=edit(open,[policy(open,{travel:false})]);advanceJourneys(open);assert.equal(open.journeys!.lastDay!.entries[0].status,'border-closed');assert.equal(open.tiles[0].properties.mana,50);assert.equal(open.journeys!.active[0].cargo[0].amount,10);assert.equal(open.journeys!.active[0].remainingDays,2);});

test('food sharing and food visits obey trade independently; work and exploration obey travel',()=>{let {w,b}=setup();w=edit(w,[{kind:'settlement-food',tileId:0,deltaRations:-10000},{kind:'food-trade-configure',tileId:0,expectedVersion:0,enabled:true,settings:DEFAULT_FOOD_TRADE_SETTINGS},{kind:'neighbor-visits-configure',tileId:0,expectedVersion:0,enabled:true,settings:DEFAULT_VISIT_SETTINGS}]);const closed=edit(w,[policy(w,{travel:false})]);advanceFoodTrade(closed);assert.equal(closed.foodTrade!.lastDay!.transferred,0);advanceNeighborVisits(closed);assert.equal(closed.neighborVisits!.lastDay!.entries.some(e=>e.purpose==='food'),false);assert.ok(closed.neighborVisits!.lastDay!.entries.some(e=>e.from===0&&e.to===b));const open=edit(w,[policy(w,{trade:false})]);advanceFoodTrade(open);assert.ok(open.foodTrade!.lastDay!.transferred>0);advanceNeighborVisits(open);assert.equal(open.neighborVisits!.lastDay!.entries.some(e=>e.from===0&&e.to===b||e.from===b&&e.to===0),false);const foodVisit=edit(w,[policy(w,{travel:false,trade:false})]);advanceNeighborVisits(foodVisit);assert.ok(foodVisit.neighborVisits!.lastDay!.entries.some(e=>e.purpose==='food'));assert.equal(foodVisit.neighborVisits!.lastDay!.beforeFood,foodVisit.neighborVisits!.lastDay!.afterFood);});

test('automatic relocation stops at hostile travel edges and resumes when they reopen',()=>{let {w,b}=setup();w=edit(w,[{kind:'settlement-food',tileId:0,deltaRations:-10000},{kind:'migration-configure',tileId:0,expectedVersion:0,enabled:true,settings:DEFAULT_MIGRATION_SETTINGS}]);const closed=edit(w,[policy(w)]);advanceMigration(closed);assert.equal(closed.migration!.lastDay!.entries.length,0);const open=edit(closed,[policy(closed,{travel:false})]);advanceMigration(open);assert.equal(open.migration!.lastDay!.entries[0].to,b);assert.equal(journeyTotals(open).population,200);});

test('named routes require both channels; generic custom transfer rules remain physical/world-defined',()=>{let {w,b}=setup();w=edit(w,[stock,{kind:'field-set',tileId:0,fieldId:'mana',value:60},{kind:'resource-route-define',tileId:0,route:{id:'mana-road',version:1,label:'Mana road',tileId:0,toTileId:b,fieldId:'mana',enabled:true,everyDays:1,amount:20,reserve:10,target:50}}]);for(const flags of [{travel:true,trade:false},{travel:false,trade:true}]){const n=advance(edit(w,[policy(w,flags)]));assert.equal(n.resourceRoutes!.lastDay!.entries[0].status,'border-closed');assert.equal(n.tiles[0].properties.mana,60);}const n=advance(edit(w,[policy(w,{travel:false,trade:false})]));assert.equal(n.resourceRoutes!.lastDay!.entries[0].status,'moved');const generic=advance(edit(w,[policy(w),{kind:'rule-define',tileId:0,rule:{id:'magic',version:1,label:'Magic',tileId:0,scope:'tile',enabled:true,everyDays:1,conditions:[],effects:[{kind:'transfer',fieldId:'mana',destination:'neighbors',value:{constant:60,terms:[]}}]}}]));assert.ok(generic.tiles[b].properties.mana>0);assert.equal(generic.resourceLedger.entries[0].beforeMilli,generic.resourceLedger.entries[0].afterMilli);});

test('knowledge blockade removes only neighbor acceleration, leaving local research and archives',()=>{let {w,b}=setup();w=edit(w,[{kind:'technology-configure',tileId:0,expectedVersion:0,enabled:true,settings:DEFAULT_RESEARCH_SETTINGS},{kind:'technology-define',tileId:0,expectedVersion:1,definition:{...CULTIVATION_TECHNOLOGY,workRequired:20}},{kind:'knowledge-configure',tileId:0,expectedVersion:2,enabled:true,bonusPermille:1000},{kind:'research-assign',tileId:0,technologyId:CULTIVATION_TECHNOLOGY.id,workers:20,reserveDays:0},{kind:'research-pause',tileId:b}]);w=advance(w);w=edit(w,[{kind:'research-auto',tileId:b}]);const closed=advance(edit(w,[policy(w,{travel:false,trade:false})]));assert.equal(closed.tiles[b].research!.lastDay!.knowledgeWork,undefined);assert.equal(closed.tiles[b].research!.lastDay!.progressAdded,10);assert.equal(closed.tiles[0].research!.projects[0].completedTick,1);const open=advance(edit(w,[policy(w,{knowledge:false})]));assert.equal(open.tiles[b].research!.lastDay!.knowledgeWork,10);assert.equal(open.tiles[b].research!.projects[0].completedTick,2);});

test('policy version, scope, pure preview and saved replay/checkpoint/export are enforced',async()=>{const root=await mkdtemp(join(tmpdir(),'logos-borders-')),store=new WorldStore(root);let {w,b}=setup();try{w=edit(w,[depart(b)]);await store.save(w);const op=policy(w),hash=stateHash(w),preview=forecast(w,prop(w,[op]));assert.equal(preview.factionPreview!.borders!.enabled,true);assert.equal(preview.journeyPreview.reports[0].status,'border-closed');assert.equal(stateHash(w),hash);for(const scope of ['tile','world'] as const){const service=new PromptService(store,{name:'Border fixture',async generate(){return {kind:'proposal',message:'Borders',assumptions:[],operations:[op]};}});try{await service.start(w,{id:scope,worldId:w.id,expectedRevision:w.revision,tileId:0,scope,mode:'propose',message:'Borders'});while(service.busy)await new Promise(r=>setTimeout(r,5));assert.equal((await service.get(w,scope)).status,scope==='world'?'complete':'failed');}finally{await service.close();}}
 const p=prop(w,[op]);w=applyProposal(w,p);await store.save(w,{kind:'proposal',proposal:p});assert.throws(()=>edit(w,[op]),/Stale/);for(let i=0;i<30;i++)w=advance(w);await store.save(w,{kind:'step',days:30});assert.equal((await store.verifyHistory(w.id)).hash,stateHash(w));const cp=await store.checkpoint(w,'Border wait');assert.equal(stateHash((await store.readCheckpoint(w.id,cp.id)).world),stateHash(w));assert.equal(stateHash((await unpackBundle(await store.exportBundle(w.id))).world),stateHash(w));}finally{await rm(root,{recursive:true,force:true});}});

test('without transport systems, active borders never alter weather, hydrology or population',()=>{let {w}=setup(),blocked=edit(w,[policy(w)]);for(let i=0;i<20;i++){w=advance(w);blocked=advance(blocked);assert.deepEqual(blocked.tiles,w.tiles);}});
