import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createWorld} from '../packages/worldgen/src/index.js';import {advance,applyProposal,validateWorld} from '../packages/engine/src/index.js';import {ProposalSchema,type World,type Operation} from '../packages/contracts/src/index.js';import {DEFAULT_SETTLEMENT_SETTINGS} from '../packages/contracts/src/settlement-defaults.js';import {DEFAULT_MIGRATION_SETTINGS} from '../packages/contracts/src/migration-defaults.js';import {DEFAULT_VISIT_SETTINGS} from '../packages/contracts/src/neighbor-visit-defaults.js';import {DEFAULT_RESEARCH_SETTINGS,CULTIVATION_TECHNOLOGY} from '../packages/contracts/src/technology.js';import {DEFAULT_DISEASE_SETTINGS} from '../packages/contracts/src/disease-defaults.js';import {journeyTotals} from '../packages/engine/src/journeys.js';import {healthTotals} from '../packages/engine/src/disease.js';import {WorldStore,stateHash} from '../apps/server/src/store.js';import {forecast,PromptService} from '../apps/server/src/prompts.js';import {unpackBundle} from '../apps/server/src/portable.js';
const prop=(w:World,operations:Operation[])=>ProposalSchema.parse({id:`garrison-${w.revision}`,worldId:w.id,expectedRevision:w.revision,summary:'Garrison',operations}),edit=(w:World,ops:Operation[])=>applyProposal(w,prop(w,ops));
function setup(){let w=createWorld({id:'garrisons',name:'Garrisons',seed:'garrisons',frequency:2});w.tiles.forEach(t=>t.elevationM=1000);const b=w.cells[0].neighbors[0];w=edit(w,[...[0,b].flatMap(tileId=>[{kind:'settlement-create' as const,tileId,label:'Village',population:100,foodRations:10000,settings:{...DEFAULT_SETTLEMENT_SETTINGS,farmRationsPerDay:1000,growthPermille:0,lossPermille:0}},{kind:'rainfall' as const,tileId,mmPerDay:5},{kind:'temperature' as const,tileId,celsius:20,mode:'sustained' as const}]),{kind:'faction-define',tileId:0,expectedVersion:0,faction:{id:'oak',label:'Oak',color:'#336633'}},{kind:'faction-claim',tileId:0,factionId:'oak'}]);return {w,b};}
const config=(w:World,target=40,reserveDays=7):Operation=>({kind:'garrison-configure',tileId:0,expectedVersion:w.tiles[0].garrison?.version??0,target,reserveDays});
const depart=(b:number,population:number):Operation=>({kind:'journey-depart',tileId:0,journeyId:'party',label:'Party',path:[0,b],daysPerHop:1,population,foodRations:100,cargo:[]});

test('garrison service consumes existing healthy labor and exactly one resident meal',()=>{const {w}=setup(),n=advance(edit(w,[config(w)])),base=advance(w);assert.equal(n.tiles[0].population,100);assert.equal(n.tiles[0].garrison!.lastDay!.workers,40);assert.equal(n.tiles[0].settlement!.lastDay!.consumed,100);assert.equal(n.tiles[0].settlement!.lastDay!.potential,120);assert.equal(base.tiles[0].settlement!.lastDay!.potential,200);assert.equal(n.tiles[0].settlement!.lastDay!.garrisonWorkers,40);assert.equal(journeyTotals(n).population,200);const zero=edit(n,[config(n,0)]);assert.equal(advance(zero).tiles[0].settlement!.lastDay!.potential,200);});

test('research only receives the remaining healthy home workers after service',()=>{let {w}=setup();w=edit(w,[config(w,95),{kind:'technology-configure',tileId:0,expectedVersion:0,enabled:true,settings:DEFAULT_RESEARCH_SETTINGS},{kind:'technology-define',tileId:0,expectedVersion:1,definition:CULTIVATION_TECHNOLOGY}]);w=advance(w);assert.equal(w.tiles[0].garrison!.lastDay!.workers,95);assert.equal(w.tiles[0].research!.lastDay!.workers,5);assert.equal(w.tiles[0].settlement!.lastDay!.potential,0);});

test('service slots stay home while visits and migration retain population conservation',()=>{let {w,b}=setup();w=edit(w,[config(w,100),{kind:'neighbor-visits-configure',tileId:0,expectedVersion:0,enabled:true,settings:{...DEFAULT_VISIT_SETTINGS,dailyPermille:1000}},{kind:'migration-configure',tileId:0,expectedVersion:0,enabled:true,settings:{...DEFAULT_MIGRATION_SETTINGS,departurePermille:1000}},{kind:'settlement-food',tileId:b,deltaRations:100000}]);const n=advance(w);assert.equal(n.neighborVisits!.lastDay!.entries.some(e=>e.from===0),false);assert.equal(n.migration!.lastDay!.entries.some(e=>e.from===0),false);assert.equal(journeyTotals(n).population,200);const released=advance(edit(w,[config(w,0)]));assert.ok(released.neighborVisits!.lastDay!.entries.some(e=>e.from===0));assert.ok(released.migration!.lastDay!.entries.some(e=>e.from===0));assert.equal(journeyTotals(released).population,200);});

test('illness and contact reduce service without duplicating healthy workers or health compartments',()=>{let {w}=setup();w=edit(w,[config(w,80),{kind:'disease-configure',tileId:0,expectedVersion:0,enabled:true,settings:{...DEFAULT_DISEASE_SETTINGS,recoveryPermille:0,immunityLossPermille:0,waterExposurePermille:0}},{kind:'disease-introduce',tileId:0,count:70},{kind:'disease-contact-configure',tileId:0,expectedVersion:1,enabled:true,ratePermille:500},{kind:'neighbor-visits-configure',tileId:0,expectedVersion:0,enabled:true,settings:{...DEFAULT_VISIT_SETTINGS,dailyPermille:1000}}]);const n=advance(w),g=n.tiles[0].garrison!.lastDay!;assert.ok(g.workers<30);assert.equal(g.reserved,80);const outgoing=n.neighborVisits!.lastDay!.entries.filter(e=>e.from===0);assert.equal(outgoing.reduce((a,e)=>a+e.visitors,0),20);const homeIll=n.tiles[0].health!.ill-outgoing.reduce((a,e)=>a+(e.health?.ill??0),0);assert.ok(g.workers+homeIll<=80);assert.ok(n.tiles[0].settlement!.lastDay!.potential>=0);assert.equal(healthTotals(n).population,200);validateWorld(n);});

test('food and terrain pause service and later recover without deleting configured targets',()=>{const {w}=setup();const staffed=edit(w,[config(w,100)]);for(const op of [{kind:'settlement-food',tileId:0,deltaRations:-10000},{kind:'elevation',tileId:0,deltaM:-1500}] as Operation[]){const n=advance(edit(staffed,[op]));assert.equal(n.tiles[0].garrison!.lastDay!.workers,0);assert.equal(n.tiles[0].garrison!.target,100);assert.equal(n.tiles[0].garrison!.lastDay!.reason,op.kind==='elevation'?'terrain':'food');}let n=advance(edit(staffed,[{kind:'settlement-food',tileId:0,deltaRations:-10000}]));n=advance(edit(n,[{kind:'settlement-food',tileId:0,deltaRations:10000}]));assert.equal(n.tiles[0].garrison!.lastDay!.workers,100);const flooded=structuredClone(staffed);for(const t of flooded.tiles)t.waterL=Math.ceil(flooded.cells[t.id].areaM2*1000);assert.equal(advance(flooded).tiles[0].garrison!.lastDay!.reason,'terrain');});

test('departures respect service slots; demobilization is required before ownership or removal',()=>{let {w,b}=setup();w=edit(w,[config(w,80)]);const hash=stateHash(w);assert.throws(()=>edit(w,[depart(b,30)]),/Demobilize/);assert.equal(stateHash(w),hash);assert.equal(edit(w,[depart(b,20)]).tiles[0].population,80);assert.throws(()=>edit(w,[{kind:'faction-claim',tileId:0,factionId:null}]),/Demobilize/);assert.throws(()=>edit(w,[{kind:'settlement-remove',tileId:0,discardPopulation:100,discardFoodRations:10000}]),/Demobilize/);w=edit(w,[config(w,0),{kind:'faction-claim',tileId:0,factionId:null}]);assert.equal(w.tiles[0].factionId,undefined);w=edit(w,[{kind:'settlement-remove',tileId:0,discardPopulation:100,discardFoodRations:10000}]);assert.equal(w.tiles[0].garrison,undefined);});

test('empty/attrited populations cap service; invalid versions/claims/targets/reports reject',()=>{let {w,b}=setup();assert.throws(()=>edit(w,[config(w,101)]),/exceeds/);assert.throws(()=>edit(w,[{...config(w),tileId:b}]),/claimed/);const op=config(w,100);w=edit(w,[op]);assert.throws(()=>edit(w,[op]),/Stale/);const reduced=advance(edit(w,[{kind:'settlement-population',tileId:0,population:20}]));assert.equal(reduced.tiles[0].garrison!.lastDay!.workers,20);const empty=advance(edit(w,[{kind:'settlement-population',tileId:0,population:0}]));assert.equal(empty.tiles[0].garrison!.lastDay!.reason,'empty');const bad=structuredClone(reduced);bad.tiles[0].garrison!.lastDay!.workers=101;assert.throws(()=>validateWorld(bad),/accounting/);});

test('local scope, read-only preview, determinism, replay, checkpoint and portable save',async()=>{const root=await mkdtemp(join(tmpdir(),'logos-garrisons-')),store=new WorldStore(root);let {w}=setup();try{await store.save(w);const op=config(w),hash=stateHash(w),f=forecast(w,prop(w,[op]));assert.equal(f.factionPreview!.garrisons[0].lastDay!.workers,40);assert.equal(stateHash(w),hash);for(const [id,tileId,status] of [['local',0,'complete'],['outside',w.cells[0].neighbors[0],'failed']] as const){const service=new PromptService(store,{name:'Garrison fixture',async generate(){return {kind:'proposal',message:'Garrison',assumptions:[],operations:[{...op,tileId}]};}});try{await service.start(w,{id,worldId:w.id,expectedRevision:w.revision,tileId:0,scope:'tile',mode:'propose',message:'Service'});while(service.busy)await new Promise(r=>setTimeout(r,5));assert.equal((await service.get(w,id)).status,status);}finally{await service.close();}}const p=prop(w,[op]);w=applyProposal(w,p);await store.save(w,{kind:'proposal',proposal:p});let copy=structuredClone(w);for(let i=0;i<30;i++){w=advance(w);copy=advance(copy);}assert.equal(stateHash(w),stateHash(copy));await store.save(w,{kind:'step',days:30});assert.equal((await store.verifyHistory(w.id)).hash,stateHash(w));const cp=await store.checkpoint(w,'Garrison');assert.equal(stateHash((await store.readCheckpoint(w.id,cp.id)).world),stateHash(w));assert.equal(stateHash((await unpackBundle(await store.exportBundle(w.id))).world),stateHash(w));}finally{await rm(root,{recursive:true,force:true});}});

test('visiting workers can fill farm vacancies created by local service',()=>{let {w,b}=setup();w=edit(w,[config(w,100),{kind:'settlement-configure',tileId:0,expectedRulesVersion:1,settings:{farmRationsPerDay:200}},{kind:'neighbor-visits-configure',tileId:0,expectedVersion:0,enabled:true,settings:{...DEFAULT_VISIT_SETTINGS,dailyPermille:1000}}]);const n=advance(w),visitors=n.neighborVisits!.lastDay!.entries.filter(e=>e.to===0&&e.purpose==='work');assert.ok(visitors.some(e=>e.from===b));assert.equal(n.tiles[0].garrison!.lastDay!.workers,100);assert.equal(n.tiles[0].settlement!.lastDay!.potential,200);assert.equal(journeyTotals(n).population,200);});
