import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createWorld} from '../packages/worldgen/src/index.js';import {advance,applyProposal,validateWorld} from '../packages/engine/src/index.js';import {journeyTotals,advanceJourneys} from '../packages/engine/src/journeys.js';import {landJourneyPath} from '../packages/engine/src/journey-path.js';import {resourceTotals} from '../packages/engine/src/resources.js';
import {ProposalSchema,type World,type Operation} from '../packages/contracts/src/index.js';import {DEFAULT_SETTLEMENT_SETTINGS} from '../packages/contracts/src/settlement-defaults.js';import {WorldStore,stateHash} from '../apps/server/src/store.js';import {PromptService,forecast} from '../apps/server/src/prompts.js';import {unpackBundle} from '../apps/server/src/portable.js';import {copyWorld,worldSummary} from '../apps/server/src/world-management.js';
const proposal=(w:World,operations:Operation[])=>ProposalSchema.parse({id:`edit-${w.history.length}`,worldId:w.id,expectedRevision:w.revision,summary:'Journey change',operations});const edit=(w:World,ops:Operation[])=>applyProposal(w,proposal(w,ops));
const setup=()=>{let w=createWorld({id:'journeys',name:'Journeys',seed:'journeys',frequency:2});w.tiles.forEach(t=>t.elevationM=1000);const to=w.cells[0].neighbors[0];w=edit(w,[...([0,to].map(tileId=>({kind:'settlement-create',tileId,label:`Village ${tileId}`,population:tileId===0?100:20,foodRations:10000,settings:{...DEFAULT_SETTLEMENT_SETTINGS,capacity:1000,farmRationsPerDay:0,growthPermille:0}})) as Operation[]),{kind:'field-define',tileId:0,migration:'preserve',definition:{id:'mana',version:1,label:'Mana',unit:'motes',description:'',quantity:'stock',min:0,max:100,defaultValue:0}},{kind:'field-set',tileId:0,fieldId:'mana',value:50}]);return {w,to};};
const depart=(w:World,options:Partial<Extract<Operation,{kind:'journey-depart'}>>={}):Operation=>({kind:'journey-depart',tileId:0,journeyId:'migrants',label:'Migrants',path:[0,w.cells[0].neighbors[0]],daysPerHop:2,population:10,foodRations:100,cargo:[{fieldId:'mana',amount:5}],...options});
test('departure conserves inhabitants/food/cargo and timed arrival credits once, with one meal per person per day',()=>{
 const {w,to}=setup(),before=journeyTotals(w),hash=stateHash(w);let n=edit(w,[depart(w)]);assert.equal(journeyTotals(n).population,before.population);assert.equal(journeyTotals(n).foodRationsTotal,before.foodRationsTotal);assert.equal(resourceTotals(n)[0].totalMilli,50000);assert.equal(worldSummary(n).travelers,10);assert.equal(n.tiles[0].population,90);assert.equal(n.tiles[to].population,20);
 n=advance(n);assert.equal(n.journeys!.active[0].remainingDays,1);assert.equal(n.journeys!.active[0].foodRations,90);assert.equal(journeyTotals(n).foodRationsTotal,before.foodRationsTotal-120);
 n=advance(n);assert.equal(n.journeys!.active.length,0);assert.equal(n.tiles[to].population,30);assert.equal(n.tiles[to].properties.mana,5);assert.equal(journeyTotals(n).population,120);assert.equal(journeyTotals(n).foodRationsTotal,before.foodRationsTotal-240);assert.equal(n.journeys!.lastDay!.entries[0].consumed,0);assert.equal(n.journeys!.lastDay!.entries[0].tileId,to);assert.equal(advance(n).tiles[to].population,30);assert.equal(resourceTotals(n)[0].totalMilli,50000);assert.equal(stateHash(w),hash);
});
test('blocked legs preserve progress; provisioning, redirection and docking recover parties without creating inventory',()=>{
 const {w,to}=setup();let n=edit(w,[depart(w),{kind:'travel-permission',tileId:to,allowed:false}]);n=advance(n);assert.equal(n.journeys!.active[0].remainingDays,2);assert.equal(n.journeys!.lastDay!.entries[0].status,'closed');const total=journeyTotals(n).foodRationsTotal;n=edit(n,[{kind:'journey-provision',tileId:0,journeyId:'migrants',foodRations:50}]);assert.equal(journeyTotals(n).foodRationsTotal,total);assert.equal(n.journeys!.active[0].foodRations,140);
 n=edit(n,[{kind:'journey-redirect',tileId:0,journeyId:'migrants',path:[0,to],daysPerHop:3}]);assert.equal(n.journeys!.active[0].remainingDays,3);const pop=journeyTotals(n).population;n=edit(n,[{kind:'journey-dock',tileId:0,journeyId:'migrants'}]);assert.equal(n.journeys!.active.length,0);assert.equal(journeyTotals(n).population,pop);assert.equal(n.tiles[0].properties.mana,50);
});
test('destination capacity, missing settlements, food and stock bounds cause explicit waiting and later arrival',()=>{
 for(const [operation,status] of [[{kind:'settlement-configure',tileId:setup().to,expectedRulesVersion:1,settings:{capacity:20}},'population-capacity'],[{kind:'settlement-remove',tileId:setup().to,discardPopulation:20,discardFoodRations:10000},'no-settlement'],[{kind:'field-set',tileId:setup().to,fieldId:'mana',value:100},'cargo-capacity'],[{kind:'elevation',tileId:setup().to,deltaM:-1000},'submerged']] as [Operation,string][]){const {w}=setup();let n=edit(w,[depart(w,{daysPerHop:1}),operation]);n=advance(n);assert.equal(n.journeys!.active.length,1);assert.equal(n.journeys!.lastDay!.entries[0].status,status);}
 const {w,to}=setup();let n=edit(w,[depart(w,{daysPerHop:1}),{kind:'settlement-configure',tileId:to,expectedRulesVersion:1,settings:{capacity:20}}]);n=advance(n);n=edit(n,[{kind:'settlement-configure',tileId:to,expectedRulesVersion:2,settings:{capacity:30}}]);n=advance(n);assert.equal(n.tiles[to].population,30);assert.equal(n.journeys!.active.length,0);
 let full=edit(w,[depart(w,{daysPerHop:1}),{kind:'settlement-food',tileId:to,deltaRations:999990000}]);full.tick++;advanceJourneys(full);assert.equal(full.journeys!.lastDay!.entries[0].status,'food-capacity');
});
test('travel shortages lose inhabitants explicitly; empty parties retain recoverable cargo and no births occur',()=>{
 const {w,to}=setup();let n=edit(w,[depart(w,{population:1,foodRations:0}),{kind:'travel-permission',tileId:to,allowed:false}]);for(let i=0;i<7;i++)n=advance(n);assert.equal(n.journeys!.active[0].population,0);assert.equal(n.journeys!.lastDay!.entries[0].losses,1);assert.equal(n.journeys!.lastDay!.entries[0].status,'no-travelers');assert.equal(journeyTotals(n).population,119);assert.equal(resourceTotals(n)[0].totalMilli,50000);n=edit(n,[{kind:'journey-dock',tileId:0,journeyId:'migrants'}]);assert.equal(n.tiles[0].properties.mana,50);assert.equal(n.journeys!.active.length,0);
});
test('paths, stock conversions, IDs, capacities and state failures reject atomically',()=>{
 const {w,to}=setup(),hash=stateHash(w);for(const operation of [depart(w,{population:101}),depart(w,{foodRations:10001}),depart(w,{path:[0,0,to]}),depart(w,{cargo:[{fieldId:'mana',amount:.0001}]}),depart(w,{cargo:[{fieldId:'mana',amount:30},{fieldId:'mana',amount:30}]})])assert.throws(()=>edit(w,[operation]));assert.equal(stateHash(w),hash);
 assert.throws(()=>edit(w,[depart(w),{kind:'field-define',tileId:0,migration:'preserve',definition:{...w.definitions.fields[0],version:2,max:200},transform:{scale:2,offset:0,precision:'exact'}}]),/Unload/);
 assert.throws(()=>edit(w,[depart(w),{kind:'journey-dock',tileId:0,journeyId:'migrants'},depart(w)]),/reused/);
 const n=edit(w,[depart(w)]);assert.throws(()=>edit(n,[depart(n)]),/used/);assert.throws(()=>edit(n,[{kind:'field-remove',tileId:0,fieldId:'mana'}]),/cargo/);assert.throws(()=>edit(n,[{kind:'field-define',tileId:0,migration:'preserve',definition:{...n.definitions.fields[0],version:2},transform:{scale:1,offset:0,precision:'exact'}}]),/Unload/);
 const corrupt=structuredClone(n);corrupt.journeys!.active[0].index=1;assert.throws(()=>validateWorld(corrupt),/progress/);assert.deepEqual(landJourneyPath(w,0,to),[0,to]);assert.throws(()=>landJourneyPath(edit(w,[{kind:'travel-permission',tileId:to,allowed:false}]),0,to),/Endpoints/);
});
test('long paths take full leg durations, preserve transit through checkpoints/portable/replay and do not tick offline',async()=>{
 const root=await mkdtemp(join(tmpdir(),'logos-journeys-')),store=new WorldStore(root);let {w,to}=setup();const far=w.cells[to].neighbors.find(id=>id!==0&&!w.cells[0].neighbors.includes(id))!;w=edit(w,[{kind:'settlement-create',tileId:far,label:'Far village',population:0,foodRations:0,settings:{...DEFAULT_SETTLEMENT_SETTINGS,growthPermille:0}}]);try{await store.save(w);const p=proposal(w,[depart(w,{path:[0,to,far],daysPerHop:3})]);w=applyProposal(w,p);await store.save(w,{kind:'proposal',proposal:p});for(let i=0;i<3;i++)w=advance(w);await store.save(w,{kind:'step',days:3});assert.equal(w.journeys!.active[0].index,1);assert.equal(w.tiles[far].population,0);const cp=await store.checkpoint(w,'In transit');assert.equal(stateHash(await store.load(w.id)),stateHash(w));assert.equal((await store.verifyHistory(w.id)).hash,stateHash(w));assert.equal((await store.readCheckpoint(w.id,cp.id)).world.journeys!.active[0].index,1);const bundle=await unpackBundle(await store.exportBundle(w.id)),copy=copyWorld(bundle.world,'journey-copy','Journey copy');await store.createNew(copy,undefined,bundle);assert.deepEqual(advance(await store.load(copy.id)).tiles,advance(w).tiles);for(let i=0;i<3;i++)w=advance(w);assert.equal(w.tiles[far].population,10);assert.equal(w.journeys!.active.length,0);}finally{await rm(root,{recursive:true,force:true});}
});
test('departure preview conserves immediate totals, scopes whole path and Discuss cannot mutate',async()=>{
 const root=await mkdtemp(join(tmpdir(),'logos-journey-prompts-')),store=new WorldStore(root),{w}=setup();try{await store.save(w);const preview=forecast(w,proposal(w,[depart(w)]));assert.equal(preview.journeyPreview.before.population,preview.journeyPreview.applied.population);assert.equal(preview.journeyPreview.applied.travelers,10);assert.equal(preview.resources[0].beforeMilli,50000);for(const [mode,scope,status] of [['propose','tile','failed'],['propose','neighbors','complete'],['discuss','world','failed']] as const){const service=new PromptService(store,{name:'Journey fixture',async generate(){return {kind:'proposal',message:'Depart',assumptions:[],operations:[depart(w)]};}});try{const id=`${mode}-${scope}`;await service.start(w,{id,worldId:w.id,expectedRevision:w.revision,tileId:0,scope,mode,message:'Depart'});while(service.busy)await new Promise(r=>setTimeout(r,5));assert.equal((await service.get(w,id)).status,status);assert.equal(stateHash(await store.load(w.id)),stateHash(w));}finally{await service.close();}}}finally{await rm(root,{recursive:true,force:true});}
});

test('competing arrivals use stable ID priority; redirection loses partial progress without losing supplies',()=>{
 const {w,to}=setup();let n=edit(w,[{kind:'settlement-configure',tileId:to,expectedRulesVersion:1,settings:{capacity:30}},depart(w,{journeyId:'omega',daysPerHop:1}),depart(w,{journeyId:'alpha',daysPerHop:1})]);n=advance(n);assert.equal(n.tiles[to].population,30);assert.deepEqual(n.journeys!.active.map(j=>j.id),['omega']);assert.equal(n.journeys!.lastDay!.entries.find(r=>r.journeyId==='omega')!.status,'population-capacity');assert.equal(journeyTotals(n).population,120);
 let traveling=advance(edit(w,[depart(w,{daysPerHop:3})]));assert.equal(traveling.journeys!.active[0].remainingDays,2);const totals=journeyTotals(traveling),cargo=resourceTotals(traveling);traveling=edit(traveling,[{kind:'journey-redirect',tileId:0,journeyId:'migrants',path:[0,to],daysPerHop:3}]);assert.equal(traveling.journeys!.active[0].remainingDays,3);assert.deepEqual(journeyTotals(traveling),totals);assert.deepEqual(resourceTotals(traveling),cargo);
});
