import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdtemp,rm,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {WorldStore,stateHash} from '../dist/apps/server/src/store.js';import {createWorld} from '../dist/packages/worldgen/src/index.js';import {startServer} from '../dist/apps/server/src/index.js';import {applyProposal} from '../dist/packages/engine/src/index.js';import {DEFAULT_SETTLEMENT_SETTINGS} from '../dist/packages/contracts/src/settlement-defaults.js';
const root=await mkdtemp(join(tmpdir(),'logos-journey-browser-')),store=new WorldStore(root);let world=createWorld({id:'first-world',name:'Journey garden',seed:'journey-browser',frequency:2});world.tiles.forEach(t=>t.elevationM=1000);const to=world.cells[0].neighbors[0];world=applyProposal(world,{id:'setup',worldId:world.id,expectedRevision:0,summary:'Villages',operations:[0,to].map(tileId=>({kind:'settlement-create',tileId,label:tileId===0?'Home':'Destination',population:tileId===0?100:20,foodRations:10000,settings:{...DEFAULT_SETTLEMENT_SETTINGS,growthPermille:0,farmRationsPerDay:0}}))});await store.save(world);let calls=0;
const app=await startServer({root,port:0,provider:{name:'Journey fixture',async generate(context){calls++;return {kind:'proposal',message:'Provision this party from its current village.',assumptions:[],operations:[{kind:'journey-provision',tileId:0,journeyId:context.journeys.active[0].id,foodRations:50}]};}}}),base=`http://127.0.0.1:${app.server.address().port}`,browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{await mkdir('.local/screenshots',{recursive:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Saved locally'));await page.locator('#globe').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowLeft');await page.locator('#journey-controls summary').click();await page.locator('#journey-destination').selectOption(String(to));
 const before=stateHash(await store.load(world.id));await page.locator('#journey-depart').click();await page.locator('#proposal').waitFor({state:'visible'});assert.match(await page.locator('.journey-preview').textContent(),/Apply 120 \/ 10 traveling/);assert.equal(stateHash(await store.load(world.id)),before);await page.locator('#cancel-proposal').click();assert.equal(stateHash(await store.load(world.id)),before);
 await page.locator('#journey-depart').click();await page.locator('#proposal').waitFor({state:'visible'});await page.screenshot({path:'.local/screenshots/journeys-preview.png'});await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});assert.equal((await store.load(world.id)).tiles[0].population,90);assert.match(await page.locator('.journey-note').textContent(),/10 travelers/);
 const step=async day=>{await page.locator('#step').click();await page.waitForFunction(n=>document.querySelector('#day').textContent===`DAY ${n}`,day);};await step(1);assert.equal((await store.load(world.id)).journeys.active[0].foodRations,90);
 await page.locator('#route-controls summary').click();await page.locator('#travel-permission').click();await page.locator('#proposal').waitFor({state:'visible'});await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});await step(2);assert.match(await page.locator('.journey-report').textContent(),/closed/);assert.equal((await store.load(world.id)).journeys.active[0].remainingDays,1);
 await page.locator('#chat-open').click();await page.locator('#chat-message').fill('Give this journey 50 more food rations from the settlement.');await page.locator('#chat-propose').click();await page.locator('#chat-progress').waitFor({state:'hidden'});await page.getByRole('button',{name:'Review five-day preview'}).click();await page.locator('#proposal').waitFor({state:'visible'});await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});await page.locator('#chat-close').click();assert.equal((await store.load(world.id)).journeys.active[0].foodRations,130);
 await page.locator('.journey-note').scrollIntoViewIfNeeded();await page.screenshot({path:'.local/screenshots/journeys-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('.journey-note').scrollIntoViewIfNeeded();await page.screenshot({path:'.local/screenshots/journeys-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const hash=stateHash(await store.load(world.id));await page.reload();await page.waitForFunction(()=>document.querySelector('#day').textContent==='DAY 2');assert.equal(stateHash(await store.load(world.id)),hash);await page.locator('#globe').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowLeft');await page.locator('#route-controls summary').click();await page.locator('#travel-permission').click();await page.locator('#proposal').waitFor({state:'visible'});await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});await step(3);const saved=await store.load(world.id);assert.equal(saved.journeys.active.length,0);assert.equal(saved.tiles[to].population,30);assert.match(await page.locator('.journey-report').textContent(),/arrived/);assert.equal((await store.verifyHistory(world.id)).hash,stateHash(saved));assert.equal(calls,1);assert.deepEqual(errors,[]);console.log('Journey browser passed: departure/cancel/review, transit-inclusive totals, carried meals, closure/wait, prompted provision, reload/replay, reopening/arrival, desktop/mobile and no autonomous models.');
}finally{await browser.close();await app.close();await rm(root,{recursive:true,force:true});}
