import {launchTestBrowser} from './browser-engine.mjs';import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {combinedWorld} from '../dist/tests/fixtures/phase5.js';import {WorldStore,stateHash} from '../dist/apps/server/src/store.js';import {startServer} from '../dist/apps/server/src/index.js';
const root=await mkdtemp(join(tmpdir(),'logos-panels-')),store=new WorldStore(root),world=combinedWorld(12);await store.save(world);await store.selectWorld(world.id);let calls=0;
const app=await startServer({root,host:'127.0.0.1',port:0,provider:{name:'No model expected',async generate(){calls++;throw Error('Unexpected model call');}}});
const browser=await launchTestBrowser();
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${app.server.address().port}`);await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Saved locally'));
 assert.equal(await page.locator('#inspector-section').isDisabled(),true);await page.locator('#globe').focus();await page.keyboard.press('ArrowRight');
 await page.locator('#inspector-section').selectOption('technology-controls');assert.equal(await page.locator('#technology-controls').evaluate(e=>e.open),true);assert.equal(await page.locator('#technology-controls summary').evaluate(e=>e===document.activeElement),true);
 const top=await page.locator('.inspector-tools').boundingBox(),heading=await page.locator('#technology-controls summary').boundingBox();assert.ok(heading.y>=top.y+top.height-1,'Jump target must remain below the sticky menu: '+JSON.stringify({top,heading}));
 await page.locator('#inspector-section').selectOption('disease-controls');assert.equal(await page.locator('#technology-controls').evaluate(e=>e.open),true);assert.equal(await page.locator('#disease-controls').evaluate(e=>e.open),true);
 await page.locator('#inspector-section').selectOption('terrain-heading');assert.equal(await page.evaluate(()=>document.activeElement.id),'terrain-heading');
 await page.locator('#globe').focus();await page.keyboard.press('Home');assert.equal(await page.locator('#view-status').textContent(),'Globe zoom 100%.');await page.keyboard.press('+');assert.equal(await page.locator('#view-status').textContent(),'Globe zoom 125%.');await page.keyboard.press('-');assert.equal(await page.locator('#view-status').textContent(),'Globe zoom 100%.');
 for(let i=0;i<25;i++)await page.keyboard.press('+');const capped=await page.locator('#view-status').textContent();await page.keyboard.press('+');assert.equal(await page.locator('#view-status').textContent(),capped);await page.locator('#zoom-reset').click();assert.equal(await page.locator('#view-status').textContent(),'Globe zoom 100%.');
 await mkdir('.local/screenshots',{recursive:true});await page.screenshot({path:'.local/screenshots/panels-desktop.png'});
 for(const [width,height,name] of [[390,844,'mobile'],[320,640,'narrow']]){
  await page.setViewportSize({width,height});await page.locator('#panel-globe').click();assert.equal(await page.locator('#inspector').isVisible(),false);assert.equal(await page.locator('#world-layers').isVisible(),false);
  await page.locator('#panel-layers').click();assert.equal(await page.locator('#world-layers').isVisible(),true);assert.equal(await page.locator('#inspector').isVisible(),false);await page.getByRole('button',{name:'Water',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Water',exact:true}).getAttribute('aria-pressed'),'true');
  await page.locator('#zoom-in').click();await page.locator('#zoom-reset').click();assert.equal(await page.locator('#view-status').textContent(),'Globe zoom 100%.');
  await page.locator('#panel-zone').click();assert.equal(await page.locator('#world-layers').isVisible(),false);await page.locator('#inspector-section').selectOption('settlement-controls');await page.locator('#settlement-controls summary').waitFor({state:'visible'});
  const panel=await page.locator('#inspector').boundingBox(),bar=await page.locator('#mobile-panels').boundingBox();assert.ok(panel.y>=80&&panel.y+panel.height<=bar.y);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.screenshot({path:`.local/screenshots/panels-${name}.png`});await page.locator('#panel-globe').click();await page.keyboard.press('Enter');assert.equal(await page.locator('#inspector').isVisible(),true);
 }
 await page.locator('#worlds-toggle').click();assert.equal(await page.locator('#inspector').isVisible(),false);await page.locator('#panel-zone').click();assert.equal(await page.locator('#worlds').isVisible(),false);assert.equal(await page.locator('#inspector').isVisible(),true);
 await page.locator('#inspector-section').selectOption('tile-title');await page.locator('#chat-open').click();await page.locator('#chat-message').waitFor({state:'visible'});await page.locator('#panel-layers').click();assert.equal(await page.locator('#conversation').isVisible(),false);assert.equal(await page.locator('#world-layers').isVisible(),true);
 await page.setViewportSize({width:1024,height:600});await page.locator('#skip-inspector').focus();await page.keyboard.press('Enter');await page.locator('#inspector-section').selectOption('technology-controls');
 const shortPanel=await page.locator('#inspector').boundingBox(),footer=await page.locator('footer').boundingBox();assert.ok(shortPanel.y+shortPanel.height<=footer.y);assert.equal(await page.locator('#mobile-panels').isVisible(),false);await page.screenshot({path:'.local/screenshots/panels-short-desktop.png'});
 assert.equal(stateHash(await store.load(world.id)),stateHash(world));assert.equal(calls,0);assert.deepEqual(errors,[]);console.log('Panels passed section jumps/focus, preserved expansions, sticky visibility, bounded keyboard/button zoom, exclusive mobile panels, world/conversation transitions and unchanged save.');
}finally{await browser.close();await app.close();await rm(root,{recursive:true,force:true});}
