import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {WorldStore,stateHash} from '../dist/apps/server/src/store.js';import {createWorld} from '../dist/packages/worldgen/src/index.js';import {applyProposal} from '../dist/packages/engine/src/index.js';import {pngInfo} from '../dist/apps/server/src/artwork.js';import {startServer} from '../dist/apps/server/src/index.js';
const root=await mkdtemp(join(tmpdir(),'logos-portable-browser-')),store=new WorldStore(root),png=await readFile('packages/tile-packs/public/painterly-v1/alpine.png'),hash=pngInfo(png).hash;
let world=createWorld({id:'first-world',name:'Portable forest',seed:'portable-browser',frequency:2});world.tick=1000;world.revision=1000;for(const tile of world.tiles){tile.elevationM=500;tile.vegetation=.8;}await store.save(world);await store.saveArtwork(world.id,[png]);
const proposal={id:'artwork',worldId:world.id,expectedRevision:world.revision,summary:'Pinned alpine forest',operations:[{kind:'artwork-activate',tileId:0,pack:{id:'alpine-forest',version:1,label:'Alpine forest',credit:'Original Logos',images:[{slot:'forest',hash}]}}]};world=applyProposal(world,proposal);await store.save(world,{kind:'proposal',proposal});const original=stateHash(world);
let calls=0;const app=await startServer({root,port:0,provider:{name:'No calls',async generate(){calls++;throw Error('No model required');}}}),base=`http://127.0.0.1:${app.server.address().port}`,browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const pixels=page=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>{const gl=document.querySelector('#globe').getContext('webgl2'),data=new Uint8Array(200*200*4);gl.readPixels(Math.floor(gl.drawingBufferWidth/2)-100,Math.floor(gl.drawingBufferHeight/2)-100,200,200,gl.RGBA,gl.UNSIGNED_BYTE,data);let n=2166136261;for(const b of data)n=Math.imul(n^b,16777619);resolve(n>>>0);})));
try{
 await mkdir('.local/screenshots',{recursive:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);const ready=()=>page.waitForFunction(()=>document.querySelector('#art-status').textContent.includes('42 / 42'));await ready();const before=await pixels(page);
 await page.locator('#worlds-toggle').click();const downloading=page.waitForEvent('download');await page.locator('#export-world').click();const download=await downloading,buffer=await readFile(await download.path()),archive=JSON.parse(buffer);assert.equal(archive.version,2);assert.equal(archive.payload.images.length,1);
 await page.locator('#copy-name').fill('Imported forest');const upload=()=>page.locator('#import-world').setInputFiles({name:'forest.json',mimeType:'application/json',buffer});await upload();await page.locator('#world-review').waitFor({state:'visible'});assert.match(await page.locator('#world-review-note').textContent(),/1 images and 2 replay records/);await page.screenshot({path:'.local/screenshots/portable-review.png'});await page.locator('#cancel-world-review').click();assert.equal((await store.list()).length,1);await upload();await page.locator('#world-review').waitFor({state:'visible'});await page.locator('#apply-world-review').click();await page.locator('#world-review').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('#world-name').textContent==='Imported forest');await ready();assert.equal(await pixels(page),before);
 await page.reload();await ready();assert.equal(await pixels(page),before);await page.locator('#worlds-toggle').click();await page.locator('#source-history > summary').click();await page.locator('#source-list summary').click();await page.getByRole('button',{name:'Load source records',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#source-list').textContent.includes('Pinned alpine forest'));assert.match(await page.locator('#source-list').textContent(),/Pinned alpine forest/);await page.screenshot({path:'.local/screenshots/portable-source-history.png'});
 const downloadingAgain=page.waitForEvent('download');await page.locator('#export-world').click();const second=JSON.parse(await readFile(await(await downloadingAgain).path(),'utf8'));assert.equal(second.payload.origins.length,1);assert.equal(second.payload.origins[0].world.id,'first-world');assert.equal(second.payload.images.length,1);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/screenshots/portable-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(stateHash(await store.load(world.id)),original);assert.equal(calls,0);assert.deepEqual(errors,[]);
 console.log('Portable browser passed: full download/review/cancel/import, GPU image equality, reload, read-only original history, re-export provenance, mobile and no model calls/source mutation.');
}finally{await browser.close();await app.close();await rm(root,{recursive:true,force:true});}
