import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createWorld} from '../packages/worldgen/src/index.js';import {advance,applyProposal} from '../packages/engine/src/index.js';import {ProposalSchema,type World,type Operation} from '../packages/contracts/src/index.js';import type {ResourceRoute} from '../packages/contracts/src/routes.js';import {WorldStore,stateHash} from '../apps/server/src/store.js';import {forecast,PromptService} from '../apps/server/src/prompts.js';import {unpackBundle} from '../apps/server/src/portable.js';import {copyWorld} from '../apps/server/src/world-management.js';
const make=()=>{const w=createWorld({id:'routes',name:'Routes',seed:'routes',frequency:2});w.tiles.forEach(t=>t.elevationM=1000);return w;};
const proposal=(w:World,operations:Operation[])=>ProposalSchema.parse({id:`edit-${w.history.length}`,worldId:w.id,expectedRevision:w.revision,summary:'Resource routes',operations});const edit=(w:World,ops:Operation[])=>applyProposal(w,proposal(w,ops));
const field:Operation={kind:'field-define',tileId:0,migration:'preserve',definition:{id:'mana',version:1,label:'Mana',unit:'motes',description:'',quantity:'stock',min:0,max:100,defaultValue:0}};
const route=(w:World,overrides:Partial<ResourceRoute>={}):Operation=>({kind:'resource-route-define',tileId:overrides.tileId??0,route:{id:'mana-road',version:1,label:'Mana road',tileId:0,toTileId:w.cells[0].neighbors[0],fieldId:'mana',enabled:true,everyDays:1,amount:20,reserve:10,target:50,...overrides}});
const setup=()=>{const w=make();return edit(w,[field,{kind:'field-set',tileId:0,fieldId:'mana',value:60},route(w)]);};
const stock=(w:World,id:number)=>w.tiles[id].properties.mana??0;
test('routes preserve stock, capacity, source reserves and destination targets with exact reports',()=>{
 const w=setup(),to=w.cells[0].neighbors[0],hash=stateHash(w);let n=advance(w);assert.equal(stock(n,0),40);assert.equal(stock(n,to),20);assert.equal(n.resourceRoutes!.lastDay!.entries[0].amountMilli,20000);assert.equal(n.resourceLedger.entries[0].transferredMilli,20000);n=advance(advance(n));assert.equal(stock(n,0),10);assert.equal(stock(n,to),50);assert.equal(advance(n).resourceRoutes!.lastDay!.entries[0].status,'limited');assert.equal(stateHash(w),hash);
 const p=forecast(w,proposal(w,[{kind:'travel-permission',tileId:to,allowed:false}]));assert.equal(p.routePreview!.entries[0].status,'closed');assert.equal(stateHash(w),hash);
 const fractional=edit(w,[route(w,{version:2,amount:.001,reserve:0})]);assert.equal(advance(fractional).resourceRoutes!.lastDay!.entries[0].amountMilli,1);
});
test('legacy and named transfers share budgets and cannot forward same-day receipts across channels',()=>{
 let w=setup();const mid=w.cells[0].neighbors[0],end=w.cells[mid].neighbors.find(id=>id!==0&&!w.cells[0].neighbors.includes(id))!;
 w=edit(w,[route(w,{id:'second',tileId:mid,toTileId:end,reserve:0,amount:100,target:100})]);const n=advance(w);assert.equal(stock(n,end),0);assert.equal(n.resourceRoutes!.lastDay!.entries.find(e=>e.routeId==='second')!.amountMilli,0);
 const generic:Operation={kind:'rule-define',tileId:0,rule:{id:'legacy-share',version:1,label:'Legacy share',tileId:0,scope:'tile',enabled:true,everyDays:1,conditions:[],effects:[{kind:'transfer',fieldId:'mana',destination:'neighbors',value:{constant:60,terms:[]}}]}};
 w=edit(w,[generic]);const shared=advance(w);assert.equal(stock(shared,0),0);assert.equal(stock(shared,end),0);assert.equal(shared.resourceRoutes!.lastDay!.entries.every(e=>e.amountMilli===0),true);assert.equal(shared.resourceLedger.entries[0].beforeMilli,shared.resourceLedger.entries[0].afterMilli);
 let competing=setup();competing=edit(competing,[route(competing,{id:'second',amount:100,reserve:0,target:100})]);const result=advance(competing);assert.equal(stock(result,0),0);assert.equal(stock(result,mid),60);
});
test('permissions, terrain, cadence and pause are independent of communication and generic sharing',()=>{
 const w=setup(),to=w.cells[0].neighbors[0];
 for(const [op,status] of [[{kind:'travel-permission',tileId:0,allowed:false},'closed'],[{kind:'travel-permission',tileId:to,allowed:false},'closed'],[{kind:'elevation',tileId:to,deltaM:-1000},'submerged'],[route(w,{version:2,enabled:false}),'paused'],[route(w,{version:2,everyDays:2}),'not-due']] as [Operation,string][]){const n=advance(edit(w,[op]));assert.equal(n.resourceRoutes!.lastDay!.entries[0].status,status);assert.equal(stock(n,0),60);}
 const silent=edit(w,[{kind:'communication',tileId:0,enabled:false},{kind:'food-trade-permission',tileId:0,allowed:false}]);assert.equal(advance(silent).resourceRoutes!.lastDay!.entries[0].status,'moved');
 const paused=edit(w,[{kind:'travel-permission',tileId:0,allowed:false}]);const manual=edit(paused,[{kind:'field-transfer',tileId:0,toTileId:to,fieldId:'mana',amount:2}]);assert.equal(stock(manual,to),2);
 const scheduled=edit(w,[route(w,{version:2,everyDays:2})]);assert.equal(advance(advance(scheduled)).resourceRoutes!.lastDay!.entries[0].status,'moved');
});
test('versions, units, dependencies and invalid routes reject atomically, including recreation',()=>{
 const w=setup(),hash=stateHash(w);for(const op of [route(w),route(w,{version:2,toTileId:0}),route(w,{version:2,amount:.0001}),route(w,{version:2,target:101}),route(w,{version:2,fieldId:'missing'}),{kind:'field-remove',tileId:0,fieldId:'mana'}] as Operation[])assert.throws(()=>edit(w,[op]));assert.equal(stateHash(w),hash);
 const removed=edit(w,[{kind:'resource-route-remove',tileId:0,routeId:'mana-road'}]);assert.equal(stock(removed,0),60);assert.throws(()=>edit(removed,[route(removed)]),/version/);assert.equal(edit(removed,[route(removed,{version:2})]).resourceRoutes!.routes[0].version,2);
 const conversion:Operation={kind:'field-define',tileId:0,migration:'preserve',definition:{...w.definitions.fields[0],version:2,max:1},transform:{scale:.01,offset:0,precision:'exact'}};assert.throws(()=>edit(w,[conversion]),/resource route/);const converted=edit(w,[conversion,route(w,{version:2,amount:.2,reserve:.1,target:.5})]);assert.equal(stock(advance(converted),0),.4);
});
test('production is shared, recipient exports do not free target space, and legacy worlds stay inactive',()=>{
 const w=setup(),to=w.cells[0].neighbors[0];const full=edit(w,[{kind:'field-set',tileId:to,fieldId:'mana',value:100},route(w,{version:2,target:100}),route(w,{id:'return',tileId:to,toTileId:0,amount:100,reserve:0,target:100})]);const n=advance(full);assert.equal(n.resourceRoutes!.lastDay!.entries.find(e=>e.routeId==='mana-road')!.amountMilli,0);assert.equal(stock(n,0),100);assert.equal(stock(n,to),60);
 const production=edit(w,[{kind:'field-set',tileId:0,fieldId:'mana',value:0},{kind:'rule-define',tileId:0,rule:{id:'produce',version:1,label:'Production',tileId:0,scope:'tile',enabled:true,everyDays:1,conditions:[],effects:[{kind:'add',fieldId:'mana',value:{constant:30,terms:[]}}]}}]);assert.equal(stock(advance(production),to),20);
 assert.equal(advance(make()).resourceRoutes,undefined);assert.equal(advance(make()).tiles[0].travelAllowed,undefined);
});
test('route histories, checkpoints and portable worlds reproduce future states',async()=>{
 const root=await mkdtemp(join(tmpdir(),'logos-routes-')),store=new WorldStore(root);let w=make();try{await store.save(w);const p=proposal(w,[field,{kind:'field-set',tileId:0,fieldId:'mana',value:60},route(w)]);w=applyProposal(w,p);await store.save(w,{kind:'proposal',proposal:p});const cp=await store.checkpoint(w,'Routes');for(let i=0;i<20;i++)w=advance(w);await store.save(w,{kind:'step',days:20});assert.equal((await store.verifyHistory(w.id)).hash,stateHash(w));assert.equal((await store.readCheckpoint(w.id,cp.id)).world.resourceRoutes!.routes.length,1);const bundle=await unpackBundle(await store.exportBundle(w.id)),copy=copyWorld(bundle.world,'route-copy','Route copy');await store.createNew(copy,undefined,bundle);assert.deepEqual(advance(await store.load(copy.id)).tiles,advance(w).tiles);}finally{await rm(root,{recursive:true,force:true});}
});
test('prompt scope covers both endpoints and Discuss cannot propose routes',async()=>{
 const root=await mkdtemp(join(tmpdir(),'logos-route-prompt-')),store=new WorldStore(root),w=setup();try{await store.save(w);for(const [mode,scope,status] of [['propose','tile','failed'],['propose','neighbors','complete'],['discuss','world','failed']] as const){const service=new PromptService(store,{name:'Route fixture',async generate(){return {kind:'proposal',message:'Update route',assumptions:[],operations:[route(w,{version:2})]};}});try{const id=`${mode}-${scope}`;await service.start(w,{id,worldId:w.id,expectedRevision:w.revision,tileId:0,scope,mode,message:'Update route'});while(service.busy)await new Promise(r=>setTimeout(r,5));assert.equal((await service.get(w,id)).status,status);assert.equal(stateHash(await store.load(w.id)),stateHash(w));}finally{await service.close();}}}finally{await rm(root,{recursive:true,force:true});}
});
