import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdtemp,rm,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {WorldStore,stateHash} from '../dist/apps/server/src/store.js';import {createWorld} from '../dist/packages/worldgen/src/index.js';import {startServer} from '../dist/apps/server/src/index.js';import {applyProposal} from '../dist/packages/engine/src/index.js';
const root=await mkdtemp(join(tmpdir(),'logos-route-browser-')),store=new WorldStore(root);let world=createWorld({id:'first-world',name:'Route garden',seed:'routes-browser',frequency:2});world.tiles.forEach(t=>t.elevationM=1000);const neighbor=world.cells[0].neighbors[0];world=applyProposal(world,{id:'setup',worldId:world.id,expectedRevision:0,summary:'Mana stock',operations:[{kind:'field-define',tileId:0,migration:'preserve',definition:{id:'mana',version:1,label:'Mana',unit:'motes',description:'',quantity:'stock',min:0,max:100,defaultValue:0}},{kind:'field-set',tileId:0,fieldId:'mana',value:60}]});await store.save(world);let calls=0;
const app=await startServer({root,port:0,provider:{name:'Route fixture',async generate(context){calls++;const r=context.resourceRoutes.routes[0];return {kind:'proposal',message:'Pause this resource route.',assumptions:[],operations:[{kind:'resource-route-define',tileId:0,route:{...r,version:r.version+1,enabled:false}}]};}}}),base=`http://127.0.0.1:${app.server.address().port}`,browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{await mkdir('.local/screenshots',{recursive:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Saved locally'));await page.locator('#globe').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowLeft');await page.locator('#route-controls summary').click();await page.locator('#route-amount').fill('20');await page.locator('#route-reserve').fill('10');await page.locator('#route-target').fill('50');await page.locator('#route-destination').selectOption(String(neighbor));
 const before=stateHash(await store.load(world.id));await page.locator('#route-create').click();await page.locator('#proposal').waitFor({state:'visible'});assert.match(await page.locator('.route-preview').textContent(),/20 motes; delivered/);assert.equal(stateHash(await store.load(world.id)),before);await page.locator('#cancel-proposal').click();assert.equal(stateHash(await store.load(world.id)),before);
 await page.locator('#route-create').click();await page.locator('#proposal').waitFor({state:'visible'});await page.screenshot({path:'.local/screenshots/routes-preview.png'});await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});assert.equal((await store.load(world.id)).tiles[0].properties.mana,60);
 const step=async day=>{await page.locator('#step').click();await page.waitForFunction(n=>document.querySelector('#day').textContent===`DAY ${n}`,day);};await step(1);assert.equal((await store.load(world.id)).tiles[neighbor].properties.mana,20);assert.match(await page.locator('.resource-route-note').textContent(),/20 motes, delivered/);
 await page.locator('#travel-permission').click();await page.locator('#proposal').waitFor({state:'visible'});assert.match(await page.locator('.route-preview').textContent(),/travel closed/);await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});await step(2);assert.equal((await store.load(world.id)).tiles[neighbor].properties.mana,20);
 await page.locator('#travel-permission').click();await page.locator('#proposal').waitFor({state:'visible'});await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});await step(3);assert.equal((await store.load(world.id)).tiles[neighbor].properties.mana,40);
 await page.locator('#chat-open').click();await page.locator('#chat-scope').selectOption('neighbors');await page.locator('#chat-message').fill('Pause the resource route.');await page.locator('#chat-propose').click();await page.locator('#chat-progress').waitFor({state:'hidden'});await page.getByRole('button',{name:'Review five-day preview'}).click();await page.locator('#proposal').waitFor({state:'visible'});assert.match(await page.locator('.route-preview').textContent(),/route paused/);await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});await page.locator('#chat-close').click();await step(4);assert.equal((await store.load(world.id)).tiles[neighbor].properties.mana,40);
 await page.locator('.resource-route-note').scrollIntoViewIfNeeded();await page.screenshot({path:'.local/screenshots/routes-desktop.png'});await page.setViewportSize({width:390,height:844});await page.locator('.resource-route-note').scrollIntoViewIfNeeded();await page.screenshot({path:'.local/screenshots/routes-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const hash=stateHash(await store.load(world.id));await page.reload();await page.waitForFunction(()=>document.querySelector('#day').textContent==='DAY 4');assert.equal(stateHash(await store.load(world.id)),hash);assert.equal((await store.verifyHistory(world.id)).hash,hash);assert.equal(calls,1);assert.deepEqual(errors,[]);console.log('Routes browser passed: reviewed creation/cancel, exact routes and conservation, travel closure/reopening, prompted pause, reload/replay, desktop/mobile and no autonomous models.');
}finally{await browser.close();await app.close();await rm(root,{recursive:true,force:true});}
