import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {WorldStore,stateHash} from '../dist/apps/server/src/store.js';import {createWorld} from '../dist/packages/worldgen/src/index.js';import {applyProposal,advance} from '../dist/packages/engine/src/index.js';import {ProposalSchema} from '../dist/packages/contracts/src/index.js';import {startServer} from '../dist/apps/server/src/index.js';
const root=await mkdtemp(join(tmpdir(),'logos-selective-browser-')),store=new WorldStore(root);let source=createWorld({id:'first-world',name:'Source valley',seed:'selective-browser',frequency:2});await store.save(source);
const apply=async(w,summary,operations)=>{const p=ProposalSchema.parse({id:`edit-${w.revision}`,worldId:w.id,expectedRevision:w.revision,summary,operations}),next=applyProposal(w,p);await store.save(next,{kind:'proposal',proposal:p});return next;};
source=await apply(source,'Drench valley',[{kind:'rainfall',tileId:0,mmPerDay:30}]);source=advance(advance(source));await store.save(source,{kind:'step',days:2});source=await apply(source,'Isolate neighbor',[{kind:'communication',tileId:1,enabled:false}]);source=advance(source);await store.save(source,{kind:'step',days:1});const sourceHash=stateHash(source);
let dependency=createWorld({id:'dependent',name:'Dependent',seed:'dep',frequency:2});await store.save(dependency);dependency=await apply(dependency,'Define mana',[{kind:'field-define',tileId:0,migration:'preserve',definition:{id:'mana',version:1,label:'Mana',unit:'units',description:'',min:0,max:100,defaultValue:0}}]);dependency=await apply(dependency,'Add mana',[{kind:'field-set',tileId:0,fieldId:'mana',value:20}]);
let calls=0;const app=await startServer({root,port:0,provider:{name:'No model calls',async generate(){calls++;throw Error('Unexpected model call');}}}),base=`http://127.0.0.1:${app.server.address().port}`,browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 await mkdir('.local/screenshots',{recursive:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Saved locally'));await page.locator('#worlds-toggle').click();await page.locator('#world-history > summary').click();
 const row=page.locator('.history-row').filter({hasText:'Drench valley'});await row.getByRole('button',{name:'Review without this',exact:true}).click();await page.locator('#world-review').waitFor({state:'visible'});assert.match(await page.locator('#world-review-note').textContent(),/Omit: Drench valley.*Replay 3 days/);assert.equal((await store.list()).length,2);assert.equal(stateHash(await store.load(source.id)),sourceHash);await page.screenshot({path:'.local/screenshots/selective-omit-review.png'});await page.locator('#cancel-world-review').click();
 await page.locator('#copy-name').fill('Gentler valley');await row.getByRole('button',{name:'Replace intervention',exact:true}).click();await row.locator('textarea').waitFor();assert.match(await row.locator('textarea').inputValue(),/rainfall/);await row.locator('input').fill('Gentle rain');await row.locator('textarea').fill(JSON.stringify([{kind:'rainfall',tileId:0,mmPerDay:5}]));await row.getByRole('button',{name:'Review replacement replay',exact:true}).click();await page.locator('#world-review').waitFor({state:'visible'});assert.match(await page.locator('.replay-diff').textContent(),/Replacement: Zone 0: 5 mm rain/);assert.equal(stateHash(await store.load(source.id)),sourceHash);await page.screenshot({path:'.local/screenshots/selective-replace-review.png'});await page.locator('#apply-world-review').click();await page.locator('#world-review').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('#world-name').textContent==='Gentler valley');
 const alternate=(await store.list()).find(w=>w.name==='Gentler valley');assert.ok(alternate);const saved=await store.load(alternate.id);assert.equal(saved.tiles[0].rainMm,5);assert.equal(saved.tiles[1].communication,false);assert.equal((await store.verifyHistory(alternate.id)).days,3);await page.reload();await page.waitForFunction(()=>document.querySelector('#world-name').textContent==='Gentler valley');
 await page.locator('#worlds-toggle').click();await page.getByRole('button',{name:'Dependent · day 0',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#world-name').textContent==='Dependent');await page.locator('#worlds-toggle').click();if(!await page.locator('#world-history').evaluate(e=>e.open))await page.locator('#world-history > summary').click();await page.locator('.history-row').filter({hasText:'Define mana'}).getByRole('button',{name:'Review without this',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('not skipped'));assert.match(await page.locator('#toast').textContent(),/Add mana/);assert.equal((await store.list()).length,3);
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/screenshots/selective-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(stateHash(await store.load(source.id)),sourceHash);assert.equal(calls,0);assert.deepEqual(errors,[]);
 console.log('Selective browser passed: omit review/cancel, editable replacement preview, independent branch/reload/verified journal, explicit dependency failure, mobile, source preservation and zero model calls.');
}finally{await browser.close();await app.close();await rm(root,{recursive:true,force:true});}
