import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {mkdtemp,rm,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {WorldStore,stateHash} from '../dist/apps/server/src/store.js';import {createWorld} from '../dist/packages/worldgen/src/index.js';import {startServer} from '../dist/apps/server/src/index.js';
const root=await mkdtemp(join(tmpdir(),'logos-settlements-browser-')),store=new WorldStore(root),world=createWorld({id:'first-world',name:'Settlement garden',seed:'settlement-browser',frequency:2});
world.tiles[0].elevationM=1000;world.rules=[{id:'rain-0',kind:'rainfall',tileId:0,mmPerDay:5},{id:'temperature-0',kind:'temperature',tileId:0,celsius:20}];await store.save(world);let calls=0;
const app=await startServer({root,port:0,provider:{name:'Settlement fixture',async generate(context){calls++;assert.equal(context.tiles[0].settlement.rulesVersion,1);return {kind:'proposal',message:'Set farm capacity to 200 rations/day and capacity to 100; shorten the surplus growth interval to two days.',assumptions:['Other settlement settings remain unchanged.'],operations:[{kind:'settlement-configure',tileId:context.selectedTileId,expectedRulesVersion:1,settings:{farmRationsPerDay:200,capacity:100,growthIntervalDays:2}}]};}}}),base=`http://127.0.0.1:${app.server.address().port}`,browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{await mkdir('.local/screenshots',{recursive:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('Saved locally'));await page.locator('#globe').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowLeft');
 await page.locator('#settlement-controls summary').click();await page.locator('#settlement-label').fill('Greenhaven');await page.locator('#settlement-initial-food').fill('0');await page.locator('#settlement-farms').fill('0');
 await page.locator('#settlement-create').click();await page.locator('#proposal').waitFor({state:'visible'});assert.match(await page.locator('.settlement-preview').textContent(),/shortage 5\/7 days/);assert.equal(stateHash(await store.load(world.id)),stateHash(world));await page.locator('#cancel-proposal').click();assert.equal((await store.load(world.id)).tiles[0].population,0);
 await page.locator('#settlement-create').click();await page.locator('#proposal').waitFor({state:'visible'});await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});assert.match(await page.locator('.settlement-inspector').textContent(),/100 \/ 1,000/);assert.equal(await page.locator('#settlement-create-controls').isVisible(),false);
 const step=async day=>{await page.locator('#step').click();await page.waitForFunction(n=>document.querySelector('#day').textContent===`DAY ${n}`,day);};
 for(let day=1;day<=7;day++)await step(day);assert.equal((await store.load(world.id)).tiles[0].population,99);assert.match(await page.locator('.settlement-ledger').textContent(),/1 lost = 99/);
 await page.locator('#settlement-food').click();await page.locator('#proposal').waitFor({state:'visible'});assert.equal((await store.load(world.id)).tiles[0].settlement.foodRations,0);await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});assert.equal((await store.load(world.id)).tiles[0].settlement.foodRations,700);
 await page.locator('#chat-open').click();await page.locator('#chat-message').fill('Adjust farming and growth settings.');await page.locator('#chat-propose').click();await page.locator('#chat-progress').waitFor({state:'hidden'});await page.getByRole('button',{name:'Review five-day preview'}).click();await page.locator('#proposal').waitFor({state:'visible'});assert.match(await page.locator('.settlement-preview').textContent(),/100 inhabitants/);assert.equal((await store.load(world.id)).tiles[0].settlement.rulesVersion,1);await page.screenshot({path:'.local/screenshots/settlements-preview.png'});await page.locator('#apply-proposal').click();await page.locator('#proposal').waitFor({state:'hidden'});await page.locator('#chat-close').click();await step(8);await step(9);assert.equal((await store.load(world.id)).tiles[0].population,100);
 await page.getByRole('button',{name:'Population',exact:true}).click();await page.getByRole('button',{name:'Food reserves',exact:true}).click();await page.locator('.settlement-inspector').scrollIntoViewIfNeeded();await page.screenshot({path:'.local/screenshots/settlements-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.locator('.settlement-inspector').scrollIntoViewIfNeeded();await page.screenshot({path:'.local/screenshots/settlements-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('.settlement-inspector').evaluate(el=>el.scrollWidth>el.clientWidth+1),false);
 const saved=stateHash(await store.load(world.id));await page.reload();await page.waitForFunction(()=>document.querySelector('#day').textContent==='DAY 9');assert.equal(stateHash(await store.load(world.id)),saved);await page.locator('#globe').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowLeft');assert.match(await page.locator('.settlement-inspector').textContent(),/100 \/ 100/);assert.equal((await store.verifyHistory(world.id)).hash,saved);assert.equal(calls,1);assert.deepEqual(errors,[]);
 console.log('Settlement browser passed: explicit placement/cancel/Apply, shortage loss, reviewed food aid and prompt configuration, growth/capacity, ledgers, overlays, reload/replay, desktop/mobile and no autonomous model calls.');
}finally{await browser.close();await app.close();await rm(root,{recursive:true,force:true});}
